// Auto-generated by CustomRouteGenerator
// DO NOT EDIT - Auto-generated custom route
// ✅ ZenStack v3 ORM: Uses createClient(user) not PrismaClient
// ✅ Access Control: Respects ZenStack @@allow/@@deny rules

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/db';
import { hash } from 'bcryptjs';
import { z } from 'zod';
import { createDefaultUserPreferences } from '@/lib/user-preferences';
import type { AuthUser } from '@/lib/auth';
import { UserRole } from '../../../../lib/user-activity-logger';

const signupSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  email: z.string().email('Invalid email address'),
  password: z.string().min(6, 'Password must be at least 6 characters'),
  walletAddress: z.string().regex(/^0x[a-fA-F0-9]{40}$/, 'Invalid Ethereum address').optional(),
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validatedData = signupSchema.parse(body);

    const systemUser: AuthUser = {
      id: 'system',
      email: 'system@TKNZN.pro',
      name: 'System Admin',
      role: 'ADMIN' as any as UserRole, 
    };
    const db = await createClient(systemUser);

    // Check if user already exists
    const existingUser = await db.user.findUnique({
      where: { email: validatedData.email }
    });

    if (existingUser) {
      return NextResponse.json(
        { error: 'User with this email already exists' },
        { status: 400 }
      );
    }

    // Hash the password
    const hashedPassword = await hash(validatedData.password, 12);

    // Check if wallet address is already in use
    if (validatedData.walletAddress) {
      const existingWallet = await db.user.findFirst({
        where: { walletAddress: validatedData.walletAddress }
      });

      if (existingWallet) {
        return NextResponse.json(
          { error: 'This wallet address is already associated with another account' },
          { status: 400 }
        );
      }
    }

    // Create the user
    const user = await db.user.create({
      data: {
        email: validatedData.email,
        name: validatedData.name,
        password: hashedPassword,
        walletAddress: validatedData.walletAddress,
        authMethod: validatedData.walletAddress ? 'wallet' : 'email',
        role: 'CUSTOMER', // Always CUSTOMER for standard registration
        status: 'ACTIVE',
        isPremium: false,
        loyaltyPoints: 0,
        totalSpent: 0,
        timezone: 'America/New_York',
      },
      include: {
        preferences: true,
      }
    });

    // Initialize new user with all dependencies (Account, Preferences, etc.)
    const { initializeNewUser } = await import('@/lib/services/user-initialization');
    
    try {
      const initResult = await initializeNewUser({
        userId: user.id,
        email: user.email,
        name: user.name,
        walletAddress: validatedData.walletAddress,
        authMethod: validatedData.walletAddress ? 'wallet' : 'email',
        provider: validatedData.walletAddress ? 'wallet' : 'credentials',
        providerAccountId: validatedData.walletAddress || user.email,
        ipAddress: request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || undefined,
        userAgent: request.headers.get('user-agent') || undefined,
      });

      if (!initResult.success) {
        console.warn('⚠️ User initialization had errors:', initResult.errors);
        // Don't fail signup if initialization has minor errors
      }
    } catch (error) {
      console.error('Failed to initialize user dependencies:', user.id, error);
      // Don't fail the user creation if initialization fails
    }

    // Return success without sensitive data
    return NextResponse.json({
      success: true,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        createdAt: user.createdAt,
      }
    }, { status: 201 });

  } catch (error) {
    console.error('Signup error:', error);

    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'Validation failed', details: error.issues ?? (error as { errors?: unknown }).errors },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to create account' },
      { status: 500 }
    );
  }
}
