// Auto-generated by CustomRouteGenerator
// DO NOT EDIT - Auto-generated custom route
// ✅ ZenStack v3 ORM: Uses createClient(user) not PrismaClient
// ✅ Access Control: Respects ZenStack @@allow/@@deny rules

import { NextRequest, NextResponse } from 'next/server';
import { findOrCreateUserByWallet, verifySIWESignature, generateSIWEMessage } from '@/lib/siwe';
import { toChecksumAddress, validateAddressWithError, shortenAddress } from '@/lib/address-utils';
import { createClient } from '@/lib/db';
import { getSystemUser } from '@/lib/utils/system-user';
import { initializeNewUser } from '@/lib/services/user-initialization';
import { sessionManager } from '@/lib/services/session-manager';
import { logLoginAudit } from '@/lib/services/auth-audit';
import { encode } from 'next-auth/jwt';
import { getSessionCookieName, isSecureCookie } from '@/lib/auth-cookie-utils';

import { rateLimiters, getClientIdentifier } from '@/lib/rate-limiter';
import { getCurrentUser } from '@/lib/auth';

// Force dynamic rendering - prevents 405 on Vercel when route is incorrectly cached/optimized
export const dynamic = 'force-dynamic';
// Allow up to 60s for wallet verification (cold start + DB + SIWE verification)
export const maxDuration = 60;
// Use Node.js runtime (not Edge) - ensures full compatibility with ZenStack/DB on Vercel
export const runtime = 'nodejs';

/**
 * OPTIONS - CORS preflight for POST (some clients send preflight before wallet verify)
 */
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Max-Age': '86400',
    },
  });
}

/**
 * POST /api/auth/wallet/verify - Wallet verification with optional completeness checking
 */
export async function POST(request: NextRequest) {
  try {
    // SECURITY: Rate limiting to prevent brute force signature verification attacks
    // Use IP address as primary identifier, wallet address as secondary
    const clientId = getClientIdentifier(request);

    if (!rateLimiters.signatureVerification.checkLimit(clientId)) {
      const resetTime = rateLimiters.signatureVerification.getResetTime(clientId);
      const resetSeconds = Math.ceil(resetTime / 1000);

      console.warn(`⚠️ [Wallet Verify] Rate limit exceeded for ${clientId}`);

      return NextResponse.json(
        {
          error: 'Too many verification attempts',
          message: `Please wait ${resetSeconds} seconds before trying again`,
          retryAfter: resetSeconds,
        },
        {
          status: 429,
          headers: {
            'Retry-After': resetSeconds.toString(),
            'X-RateLimit-Limit': '5',
            'X-RateLimit-Remaining': '0',
            'X-RateLimit-Reset': new Date(Date.now() + resetTime).toISOString(),
          },
        }
      );
    }

    // Check for required environment variables first
    if (!process.env.DATABASE_URL) {
      console.error('❌ [Wallet Verify] DATABASE_URL environment variable is not set');
      return NextResponse.json(
        {
          error: 'Database connection required',
          message: 'DATABASE_URL environment variable is required for wallet authentication',
          details: process.env.NODE_ENV === 'development'
            ? 'Please ensure DATABASE_URL is set in your environment variables'
            : undefined
        },
        { status: 500 }
      );
    }

    // Safely parse JSON body to avoid 500 on invalid/missing payload
    let body: any;
    try {
      body = await request.json();
    } catch (parseError) {
      return NextResponse.json(
        { error: 'Invalid JSON payload' },
        { status: 400 }
      );
    }

    const { 
      walletAddress, 
      signature, 
      message, 
      nonce, 
      chainId = '11155111', // Default to Sepolia testnet instead of mainnet
      lookupOnly = false,
      checkCompleteness = false,
      initializeMissing = false,
      linkToSocialAccount = false // ✅ NEW: Link wallet to existing social login account
    } = body || {};

    // Validate wallet address using centralized utility
    const validation = validateAddressWithError(walletAddress);
    if (!validation.isValid) {
      return NextResponse.json(
        { error: validation.error },
        { status: 400 }
      );
    }

    // Use the checksummed address from validation
    const checksummedWalletAddress = validation.checksummedAddress!;

    const addrAbbr = shortenAddress(walletAddress);
    console.log(`🔐 [Wallet Verify] Verifying wallet: ${addrAbbr}`, {
      lookupOnly,
      checkCompleteness,
      initializeMissing,
    });

    const systemUser = await getSystemUser();
    const db = createClient(systemUser);

    // Handle lookup-only mode (for SignInWalletHandler)
    if (lookupOnly && walletAddress) {
      console.log(`🔍 [Wallet Verify] Lookup-only mode for wallet: ${walletAddress}`);
      
      const checksummedAddress = toChecksumAddress(walletAddress);
      
      let foundUser = await db.user.findUnique({
        where: { walletAddress: checksummedAddress } as any,
      });
      
      if (!foundUser) {
        const users = await db.user.findMany({
          where: {  
            OR: [
              { walletAddress: checksummedAddress },
              { walletAddress: walletAddress.toLowerCase() },
              { walletAddress: walletAddress.toUpperCase() },
            ],
          } as any,
          take: 1,
        });
        
        if (users.length > 0) {
          foundUser = users[0];
          console.log('✅ [Wallet Verify] User found with case-insensitive search');
        }
      }
      
      let isNewUser = false;
      if (!foundUser) {
        console.log('⚠️ [Wallet Verify] User not found, creating new user...');
        
        const userAgent = request.headers.get('user-agent') || undefined;
        const ipAddress = request.headers.get('x-forwarded-for') || 
                         request.headers.get('x-real-ip') || 
                         'unknown';
        
        const { user: newUser, isNewUser: newUserFlag } = await findOrCreateUserByWallet(
          checksummedAddress,
          parseInt(chainId),
          'wallet',
          {
            ipAddress,
            userAgent,
          }
        );
        
        foundUser = newUser;
        isNewUser = newUserFlag;
        
        if (isNewUser) {
          console.log('🔄 [Wallet Verify] Initializing new user dependencies...');
          await initializeNewUser({ 
            userId: foundUser?.id as string,
            email: foundUser?.email as string,
            name: foundUser?.name as string,
            walletAddress: checksummedAddress,
            provider: 'wallet',
            providerAccountId: checksummedAddress,
            ipAddress,
            userAgent,
            authMethod: 'wallet',
          } as any);
        }
        
        console.log('✅ [Wallet Verify] User created:', foundUser?.id);
      }

      let isComplete = true;
      let missingRecords: string[] = [];
      
      if (checkCompleteness) {
        console.log(`🔍 [Wallet Verify] Checking user completeness...`);
        
        try {
        const userWithRelations = await db.user.findUnique({
          where: { id: foundUser?.id as unknown as string } as any,
          include: {
            accounts: true,
            preferences: true,
            portfolio: true,
            engagementMetrics: true,
              addressBooks: true
          },
        });

        if (!userWithRelations?.accounts || (userWithRelations?.accounts as any[]).length === 0) {
          missingRecords.push('account');
        }
        if (!userWithRelations?.preferences) {
          missingRecords.push('preferences');
        }
        if (!userWithRelations?.portfolio || (userWithRelations?.portfolio as any[]).length === 0) {
          missingRecords.push('portfolio');
        }
        if (!userWithRelations?.engagementMetrics) {
          missingRecords.push('engagementMetrics');
        }
          if (!userWithRelations?.addressBooks || (userWithRelations?.addressBooks as any[]).length === 0) {
            missingRecords.push('addressBooks');
        }

        isComplete = missingRecords.length === 0;

        if (!isComplete && initializeMissing) {
            console.log(`🔄 [Wallet Verify] Initializing missing records:`, missingRecords);
          
            try {
          const userAgent = request.headers.get('user-agent') || undefined;
          const ipAddress = request.headers.get('x-forwarded-for') || 
                           request.headers.get('x-real-ip') || 
                           'unknown';

          const initResult = await initializeNewUser({
            userId: foundUser?.id as unknown as string,
            email: foundUser?.email as unknown as string,
            name: foundUser?.name as unknown as string || 'User',
            walletAddress: checksummedAddress,
                authMethod: (foundUser?.authMethod as unknown as 'email' | 'wallet' | 'social') || 'wallet',
            provider: 'wallet',
            providerAccountId: checksummedAddress,
            ipAddress,
            userAgent,
          });

          if (initResult.success) {
                try {
            const updatedUser = await db.user.findUnique({
              where: { id: foundUser?.id as unknown as string } as any,
              include: {
                accounts: true,
                preferences: true,
                portfolio: true,
                engagementMetrics: true,
                      addressBooks: true,
              },
            });

            const stillMissing: string[] = [];
            if (!updatedUser?.accounts || (updatedUser?.accounts as any[]).length === 0) stillMissing.push('account');
            if (!updatedUser?.preferences) stillMissing.push('preferences');
            if (!updatedUser?.portfolio || (updatedUser?.portfolio as any[]).length === 0) stillMissing.push('portfolio');
            if (!updatedUser?.engagementMetrics) stillMissing.push('engagementMetrics');
                  if (!updatedUser?.addressBooks || (updatedUser?.addressBooks as any[]).length === 0) stillMissing.push('addressBooks');

            isComplete = stillMissing.length === 0;
            missingRecords = stillMissing;
                } catch (recheckError) {
                  console.error(`❌ [Wallet Verify] Error rechecking completeness:`, recheckError);
                }
              }
            } catch (initError) {
              console.error(`❌ [Wallet Verify] Error initializing missing records:`, initError);
            }
          }
        } catch (completenessError) {
          console.error(`❌ [Wallet Verify] Error checking completeness:`, completenessError);
          isComplete = false;
          missingRecords = ['unknown'];
        }
      }
      
      console.log(`✅ [Wallet Verify] User found/created in lookup mode:`, foundUser?.id);
      
      // Create NextAuth JWT session token for lookup mode as well
      const secret = process.env.NEXTAUTH_SECRET || process.env.AUTH_SECRET;
      if (secret) {
        const token = await encode({
          secret,
          token: {
            id: foundUser?.id as unknown as string,
            email: foundUser?.email as unknown as string,
            name: foundUser?.name as unknown as string,
            role: foundUser?.role as unknown as string,
            authMethod: foundUser?.authMethod as unknown as string || 'wallet',
            walletAddress: checksummedAddress,
            chainId: parseInt(chainId),
            sub: foundUser?.id as unknown as string,
          },
          maxAge: 30 * 24 * 60 * 60, // 30 days
        });

        const response = NextResponse.json({
          success: true,
          user: {
            id: foundUser?.id as unknown as string,
            email: foundUser?.email as unknown as string || '',
            name: foundUser?.name as unknown as string || '',    
            walletAddress: foundUser?.walletAddress as unknown as string || '',
            role: foundUser?.role as unknown as string || '',
            authMethod: foundUser?.authMethod as unknown as string || 'wallet',
          },
          token, // ✅ Include JWT token in response for Reown AppKit compatibility
          isNewUser,
          ...(checkCompleteness ? {
            isComplete,
            missingRecords,
          } : {}),
        });

        // Set the NextAuth session token cookie (must match getToken's expected name)
        response.cookies.set(getSessionCookieName(), token, {
          httpOnly: true,
          secure: isSecureCookie(),
          sameSite: 'lax',
          maxAge: 30 * 24 * 60 * 60, // 30 days
          path: '/',
        });

        console.log(`🍪 [Wallet Verify] Session cookie set for lookup mode user: ${foundUser?.id as unknown as string}`);

        return response;
      } else {
        console.warn('⚠️ [Wallet Verify] NEXTAUTH_SECRET not set - cannot create session in lookup mode');
      }
      
      return NextResponse.json({
        success: true,
        user: {
          id: foundUser?.id as unknown as string,
          email: foundUser?.email as unknown as string,
          name: foundUser?.name as unknown as string,    
          walletAddress: foundUser?.walletAddress as unknown as string,
          role: foundUser?.role as unknown as string,
          authMethod: foundUser?.authMethod as unknown as string || 'wallet',
        },
        isNewUser,
        ...(checkCompleteness ? {
          isComplete,
          missingRecords,
        } : {}),
      });
    }

    // Parse chain ID from request (default to Sepolia testnet 11155111)
    const parsedChainIdRaw = chainId ? parseInt(chainId.toString(), 10) : 11155111;
    const parsedChainId = Number.isNaN(parsedChainIdRaw) ? 11155111 : parsedChainIdRaw;
    
    // ✅ NEW: Handle linking wallet to existing social login account
    if (linkToSocialAccount) {
      // Get current session to find the social login user
      const user = await getCurrentUser(request);
      if (!user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
      }
      
      if (!user.email) {
        return NextResponse.json(
          { error: 'No active session found. Please sign in first.' },
          { status: 401 }
        );
      }
      
      const checksummedAddress = toChecksumAddress(walletAddress);
      
      // Find existing user by email (social login user)
      const socialUser = await db.user.findUnique({
        where: { email: user.email } as any,
      });
      
      if (!socialUser) {
        return NextResponse.json(
          { error: 'User account not found' },
          { status: 404 }
        );
      }
      
      // Check if wallet is already linked to another account
      const existingWalletUser = await db.user.findUnique({
        where: { walletAddress: checksummedAddress } as any,  
      });
      
      if (existingWalletUser && existingWalletUser.id !== socialUser.id) {
        return NextResponse.json(
          { error: 'This wallet is already linked to another account' },
          { status: 400 }
        );
      }
      
      // Verify signature if provided
      if (signature && message && nonce) {
        // Allow EOA (130 hex chars) and EIP-6492/EIP-1271 (longer) for embedded/smart account
        const isValidFormat = /^0x[a-fA-F0-9]{130,}$/.test(signature);
        if (!isValidFormat) {
          return NextResponse.json(
            { error: 'Invalid signature format' },
            { status: 400 }
          );
        }
        
        const verification = await verifySIWESignature(message, signature, nonce, {
          address: checksummedAddress,
          chainId: parsedChainId,
        });
        if (!verification.success) {
          return NextResponse.json(
            { error: verification.error || 'Invalid signature' },
            { status: 400 }
          );
        }
      }
      
      // Link wallet to social login account
      const updatedUser = await db.user.update({
        where: { id: socialUser.id } as any,
        data: {
          walletAddress: checksummedAddress,
          chainId: parsedChainId,
          authMethod: socialUser.authMethod === 'google' ? 'google+wallet' : 'email+wallet',
        },
        include: {
          accounts: true,
          preferences: true,
          portfolio: true,
          engagementMetrics: true,
          addressBooks: true,
        },
      });
      
      console.log(`✅ [Wallet Verify] Wallet linked to social account: ${socialUser.email}`);
      
      // Create NextAuth JWT session token after linking wallet
      const secret = process.env.NEXTAUTH_SECRET || process.env.AUTH_SECRET;
      if (secret) {
        const token = await encode({
          secret,
          token: {
            id: updatedUser?.id as unknown as string,
            email: updatedUser?.email as unknown as string,
            name: updatedUser?.name as unknown as string,
            role: updatedUser?.role as unknown as string,
            authMethod: updatedUser?.authMethod as unknown as string || 'wallet',
            walletAddress: checksummedAddress,
            chainId: parsedChainId,
            sub: updatedUser?.id as unknown as string,
          },
          maxAge: 30 * 24 * 60 * 60, // 30 days
        });

        const response = NextResponse.json({
          success: true,
          user: {
            id: updatedUser?.id as unknown as string,
            email: updatedUser?.email as unknown as string,
            name: updatedUser?.name as unknown as string,
            walletAddress: updatedUser?.walletAddress as unknown as string,
            role: updatedUser.role,
            authMethod: updatedUser?.authMethod as unknown as string || 'wallet',
          },
          isNewUser: false,
          walletLinked: true,
        });

        // Set the NextAuth session token cookie (must match getToken's expected name)
        response.cookies.set(getSessionCookieName(), token, {
          httpOnly: true,
          secure: isSecureCookie(),
          sameSite: 'lax',
          maxAge: 30 * 24 * 60 * 60, // 30 days
          path: '/',
        });

        console.log(`🍪 [Wallet Verify] Session cookie set after wallet linking: ${updatedUser.id}`);

        return response;
      }
      
      return NextResponse.json({
        success: true,
        user: {
          id: updatedUser.id,
          email: updatedUser.email,
          name: updatedUser.name,
          walletAddress: updatedUser.walletAddress,
          role: updatedUser.role,
          authMethod: updatedUser.authMethod,
        },
        isNewUser: false,
        walletLinked: true,
      });
    }
    
    // Normal verification flow (with signature)
    // Find or create user with full database initialization
    const { user, isNewUser } = await findOrCreateUserByWallet(
      walletAddress,
      parsedChainId,
      'wallet'
    );
    
    // ⚠️ CRITICAL: Check if SIWE is enabled via environment variables
    // SIWE enforcement applies to wallet authentication only (not social logins)
    const siweEnv = process.env.NEXT_PUBLIC_SIWE;
    const siweEnableEnv = process.env.NEXT_PUBLIC_ENABLE_SIWE;
    const siweEnabled = !(
      (siweEnv && siweEnv.toLowerCase() === 'false') ||
      (siweEnableEnv && siweEnableEnv.toLowerCase() === 'false')
    );
    
    // Generate SIWE message for verification if not provided
    let siweMessage;
    if (message && nonce) {
      // Parse expiration time from SIWE message if available
      let expiresAt = new Date(Date.now() + 15 * 60 * 1000); // Default: 15 minutes
      
      // Try to extract expiration time from SIWE message
      const expirationMatch = message.match(/Expiration Time:\s*(.+)/i);
      if (expirationMatch) {
        try {
          const expirationTime = new Date(expirationMatch[1].trim());
          if (!isNaN(expirationTime.getTime())) {
            expiresAt = expirationTime;
            console.log('✅ [Wallet Verify] Extracted expiration time from SIWE message:', expiresAt.toISOString());
          }
        } catch (e) {
          console.warn('⚠️ [Wallet Verify] Could not parse expiration time from message, using default');
        }
      }
      
      // Verify nonce matches the one in the message
      const messageNonceMatch = message.match(/Nonce:\s*([a-zA-Z0-9]+)/i);
      let finalNonce = nonce; // Use request nonce by default
      if (messageNonceMatch && messageNonceMatch[1] !== nonce) {
        console.warn('⚠️ [Wallet Verify] Nonce mismatch: message has', messageNonceMatch[1], 'but request has', nonce);
        // Use the nonce from the message to ensure consistency
        finalNonce = messageNonceMatch[1];
      }
      
      siweMessage = { message, nonce: finalNonce, expiresAt };
      console.log('✅ [Wallet Verify] Using provided SIWE message with nonce:', finalNonce.substring(0, 8) + '...');
      } else {
      const domain = request.headers.get('host') || 'localhost:3000';
      const uri = `http://${domain}`;
      siweMessage = await generateSIWEMessage(
        walletAddress,
        domain,
        uri,
        parsedChainId
      );
      console.log('✅ [Wallet Verify] Generated new SIWE message with nonce:', siweMessage.nonce.substring(0, 8) + '...');
    }

    // ⚠️ CRITICAL: When SIWE is enabled, signature verification is MANDATORY for wallet authentication
    // Sessions cannot be established without valid SIWE signatures when SIWE is enabled
    if (siweEnabled) {
      // Require signature, message, and nonce when SIWE is enabled
      if (!signature || !message || !nonce) {
        console.error('❌ [Wallet Verify] SIWE is enabled but signature, message, or nonce is missing');
        return NextResponse.json(
          { 
            error: 'SIWE signature required',
            message: 'SIWE authentication is enabled. Signature, message, and nonce are required for wallet authentication.',
            details: !signature ? 'Signature is missing' : !message ? 'Message is missing' : 'Nonce is missing'
          },
          { status: 400 }
        );
      }

      // Verify signature format: EOA = 130 hex chars; EIP-6492/EIP-1271 (embedded/smart account) can be longer
      const isValidFormat = /^0x[a-fA-F0-9]{130,}$/.test(signature);
      if (!isValidFormat) {
        console.error('❌ [Wallet Verify] Invalid signature format when SIWE is enabled');
        return NextResponse.json(
          {
            error: 'Invalid signature format',
            message: 'The provided signature does not match the expected Ethereum signature format (0x + at least 130 hex characters).',
            received: {
              length: signature.length,
              startsWith: signature.substring(0, 10),
              format: 'Expected: 0x[130+ hex chars] (EOA or EIP-6492/EIP-1271)'
            }
          },
          { status: 400 }
        );
      }

      // Verify the SIWE signature (pass address/chainId for EIP-1271 smart account fallback)
      console.log('🔍 [Wallet Verify] Verifying SIWE signature...');
      const verification = await verifySIWESignature(message, signature, nonce, {
        address: toChecksumAddress(walletAddress),
        chainId: parsedChainId,
      });
      if (!verification.success) {
        console.error('❌ [Wallet Verify] SIWE signature verification failed');
        return NextResponse.json(
          { 
            error: 'Invalid signature',
            message: 'SIWE signature verification failed. Please sign the message again.',
            details: verification.error || 'The signature does not match the message and wallet address'
          },
          { status: 400 }
        );
      }
      console.log('✅ [Wallet Verify] SIWE signature verified successfully');
      
      // ⚠️ CRITICAL: Update User record with nonce and nonceExpiry after successful verification
      // This allows getSession() to validate the session has a valid SIWE nonce
      // ALWAYS update nonce when SIWE verification succeeds - this is required for one-click SIWE
      // ✅ CRITICAL FIX: Always generate NEW nonceExpiry (15 minutes from NOW) when verification succeeds
      // Don't use siweMessage.expiresAt because that's the message expiry (set when nonce was generated)
      // The nonceExpiry should be refreshed to 15 minutes from when verification succeeds
      const nonceToStore = siweMessage?.nonce || nonce;
      if (nonceToStore) {
        try {
          // ✅ ALWAYS generate fresh nonceExpiry: 15 minutes from NOW (when verification succeeds)
          // This ensures nonceExpiry is always valid for session validation, regardless of
          // how long the user took to sign the message or when the nonce was originally generated
          const nonceExpiry = new Date(Date.now() + 15 * 60 * 1000); // 15 minutes from NOW
          
          console.log('💾 [Wallet Verify] Storing nonce and nonceExpiry:', {
            userId: user.id,
            nonce: nonceToStore.substring(0, 8) + '...',
            nonceExpiry: nonceExpiry.toISOString(),
            expiresIn: Math.round((nonceExpiry.getTime() - Date.now()) / 1000 / 60) + ' minutes',
            note: 'nonceExpiry refreshed to 15 minutes from verification time (not message expiry)',
          });
          
          await db.user.update({
            where: { id: user.id } as any,
            data: {
              walletNonce: nonceToStore,
              walletNonceExpiry: nonceExpiry,
              lastWalletSignIn: new Date(),
            } as any,
          });
          
          console.log('✅ [Wallet Verify] User nonce and nonceExpiry stored successfully');
        } catch (nonceUpdateError: any) {
          console.error('❌ [Wallet Verify] CRITICAL: Failed to update user nonce:', nonceUpdateError);
          console.error('   Error details:', {
            message: nonceUpdateError.message,
            code: nonceUpdateError.code,
            userId: user.id,
          });
          // ⚠️ CRITICAL: Nonce storage failure means getSession() will return null and trigger SIWE again
          // This is a critical error that should be logged but not fail the request
          // The session will be created but without nonce, causing SIWE to prompt again on next connection
        }
      } else {
        console.error('❌ [Wallet Verify] CRITICAL: No nonce available to store after SIWE verification!');
        console.error('   siweMessage.nonce:', siweMessage?.nonce);
        console.error('   nonce parameter:', nonce);
      }
    } else {
      // SIWE is disabled - allow authentication without signature (for development/testing)
      console.warn('🚧 [Wallet Verify] SIWE disabled via NEXT_PUBLIC_SIWE=false or NEXT_PUBLIC_ENABLE_SIWE=false - skipping signature verification');
      
      // Verify signature ONLY if provided and valid format (optional when SIWE is disabled)
      // Social logins (Google OAuth, credentials) should NOT provide signatures
      // If signature is provided, validate format before attempting verification
      if (signature && message && nonce) {
      // Check if signature format is valid (EOA = 130 hex chars; EIP-6492/EIP-1271 can be longer)
      const isValidFormat = /^0x[a-fA-F0-9]{130,}$/.test(signature);
      
      if (!isValidFormat) {
        // Invalid signature format - could be OAuth callback data, transaction data, or other invalid data
        console.warn('⚠️ [Wallet Verify] Invalid signature format detected');
        console.warn('   Signature length:', signature.length, 'Expected: 132+ (0x + 130+ hex chars)');
        console.warn('   Signature starts with:', signature.substring(0, 50) + '...');

        // More comprehensive checks for invalid signature data
        const isTooLong = signature.length > 300; // Much longer than expected
        const isTooShort = signature.length < 130; // Much shorter than expected
        const hasInvalidChars = !/^0x[a-fA-F0-9]*$/.test(signature); // Non-hex characters
        const startsWithZeros = signature.startsWith('0x000000000000000000000000'); // Looks like transaction data
        const isNonWalletData = isTooLong || isTooShort || hasInvalidChars || startsWithZeros;

        if (isNonWalletData) {
          // Clearly not a wallet signature - likely social login or other auth method
          console.log('✅ [Wallet Verify] Non-wallet authentication data detected - skipping signature verification');
          console.log('   Reason:', {
            tooLong: isTooLong,
            tooShort: isTooShort,
            invalidChars: hasInvalidChars,
            startsWithZeros: startsWithZeros
          });
          // Continue without signature verification for non-wallet auth
        } else {
          // Signature format is close but invalid - return helpful error
          return NextResponse.json(
            {
              error: 'Invalid signature format. The provided signature does not match the expected Ethereum signature format (0x + 130 hex characters). Please ensure you\'re using a proper Web3 wallet and signing with personal_sign.',
              received: {
                length: signature.length,
                startsWith: signature.substring(0, 10),
                format: 'Expected: 0x[130 hex chars]'
              }
            },
            { status: 400 }
          );
        }
      } else {
        // Signature format is valid - proceed with SIWE verification
        const verification = await verifySIWESignature(message, signature, nonce, {
          address: toChecksumAddress(walletAddress),
          chainId: parsedChainId,
        });
        if (!verification.success) {
          return NextResponse.json(
            { error: verification.error || 'Invalid signature' },
            { status: 400 }
          );
        }
        
        // ⚠️ CRITICAL: Update User record with nonce and nonceExpiry even when SIWE is disabled
        // This allows getSession() to validate the session has a valid SIWE nonce
        // ✅ CRITICAL FIX: Always generate NEW nonceExpiry (15 minutes from NOW) when verification succeeds
        if (siweMessage?.nonce) {
          try {
            // ✅ ALWAYS generate fresh nonceExpiry: 15 minutes from NOW (when verification succeeds)
            const nonceExpiry = new Date(Date.now() + 15 * 60 * 1000); // 15 minutes from NOW
            
            await db.user.update({
              where: { id: user.id } as any,
              data: {
                walletNonce: siweMessage.nonce,
                walletNonceExpiry: nonceExpiry,
                lastWalletSignIn: new Date(),
              } as any,
            });
            
            console.log('✅ [Wallet Verify] User nonce updated (SIWE disabled but signature provided):', {
              userId: user.id,
              nonce: siweMessage.nonce.substring(0, 8) + '...',
            });
          } catch (nonceUpdateError: any) {
            console.error('❌ [Wallet Verify] Failed to update user nonce:', nonceUpdateError);
            // Don't fail the request - nonce update is important but not critical
          }
        }
      }
    } else {
      // No signature provided - this is acceptable when SIWE is disabled or for social logins
      console.log('ℹ️ [Wallet Verify] No signature provided - proceeding without signature verification (SIWE disabled)');
    }
    }

    console.log(`✅ Wallet verification successful: ${user.id} (${addrAbbr})`);

    // Create WalletSession + WalletConnection and record SIWE message for platform audit
    const userAgent = request.headers.get('user-agent') || undefined;
    const ipAddress = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || request.headers.get('x-real-ip') || undefined;
    let createdSessionId: string | undefined;
    try {
      const sessionData = await sessionManager.createSession({
        userId: user.id,
        walletAddress: checksummedWalletAddress,
        nonce: siweMessage.nonce,
        message: siweMessage.message,
        signature,
        chainId: parsedChainId,
        authMethod: 'wallet',
        userAgent,
        ipAddress,
        expiresIn: 30 * 24 * 60 * 60 * 1000, // 30 days
      });
      createdSessionId = sessionData.sessionId;
      console.log('✅ [Wallet Verify] WalletSession and WalletConnection created; SIWE message recorded');
    } catch (sessionErr) {
      console.error('⚠️ [Wallet Verify] Failed to create WalletSession (non-fatal):', sessionErr);
    }

    // Login audit for established session
    try {
      await logLoginAudit({
        userId: user.id,
        authMethod: 'wallet',
        walletAddress: checksummedWalletAddress,
        chainId: parsedChainId,
        sessionId: createdSessionId,
        ipAddress,
        userAgent,
        isNewUser,
        siweMessage: siweMessage.message,
      });
    } catch (auditErr) {
      console.error('⚠️ [Wallet Verify] Failed to log login audit (non-fatal):', auditErr);
    }

    // Create NextAuth JWT session token
    const secret = process.env.NEXTAUTH_SECRET || process.env.AUTH_SECRET;
    if (!secret) {
      console.error('❌ [Wallet Verify] NEXTAUTH_SECRET not set - cannot create session');
    }

    const token = await encode({
      secret: secret!,
      token: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        walletAddress: checksummedWalletAddress,
        chainId: parsedChainId,
        sub: user.id,
      },
      maxAge: 30 * 24 * 60 * 60, // 30 days
    });

    // Set the session cookie and return token in body for Reown compatibility
    const response = NextResponse.json({
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        walletAddress: walletAddress,
        chainId: parsedChainId,
      },
      message: siweMessage.message,
      nonce: siweMessage.nonce,
      token, // ✅ Include JWT token in response for Reown AppKit compatibility
      success: true,
      isNewUser,
    });

    // Set the NextAuth session token cookie (must match getToken's expected name)
    response.cookies.set(getSessionCookieName(), token, {
      httpOnly: true,
      secure: isSecureCookie(),
      sameSite: 'lax',
      maxAge: 30 * 24 * 60 * 60, // 30 days
      path: '/',
    });

    console.log(`🍪 [Wallet Verify] Session cookie set for user: ${user.id}`);

    return response;

  } catch (error) {
    // Log full error details for debugging
    console.error('❌ [Wallet Verify] Wallet verification error:', error);
    if (error instanceof Error) {
      console.error('Error name:', error.name);
      console.error('Error message:', error.message);
      console.error('Error stack:', error.stack);
    }
    
    // Provide more detailed error information
    const errorMessage = error instanceof Error ? error.message : String(error);
    const errorStack = error instanceof Error ? error.stack : undefined;
    
    // Check for specific error types
    const isDatabaseError = errorMessage.includes('Database operation') || 
                           errorMessage.includes('database connection') ||
                           errorMessage.includes('DATABASE_URL') ||
                           errorMessage.includes('Cannot find package') ||
                           errorMessage.includes('Module not found') ||
                           errorMessage.includes('ZenStack') ||
                           errorMessage.includes('schema');
    
    const isMissingEnvVar = !process.env.DATABASE_URL;
    
    return NextResponse.json(
      { 
        error: isDatabaseError || isMissingEnvVar
          ? 'Database connection required. This endpoint requires a database connection to verify wallet authentication.'
          : 'Internal server error',
        message: isMissingEnvVar 
          ? 'DATABASE_URL environment variable is not set'
          : isDatabaseError
          ? 'Database connection failed. Please check your DATABASE_URL configuration.'
          : errorMessage,
        details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
        stack: process.env.NODE_ENV === 'development' ? errorStack : undefined
      },
    { status: 500 }
  );
}
}
