//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * NextAuth Account — links external OAuth/wallet providers to a User
 */
export type Account = $ModelResult<$Schema, "Account">;
/**
 * NextAuth Session — tracks active browser sessions
 */
export type Session = $ModelResult<$Schema, "Session">;
/**
 * Email verification token
 */
export type VerificationToken = $ModelResult<$Schema, "VerificationToken">;
/**
 * Password reset token (forgot-password flow). Create/read/update via system or PLATFORM_ADMIN.
 */
export type PasswordResetToken = $ModelResult<$Schema, "PasswordResetToken">;
/**
 * AppKit WalletConnect session (SIWE — Sign-In with Ethereum)
 */
export type WalletSession = $ModelResult<$Schema, "WalletSession">;
/**
 * Historical record of wallet connections
 */
export type WalletConnection = $ModelResult<$Schema, "WalletConnection">;
/**
 * User behavior / activity log (login, logout, account_created, etc.). Users can read their own.
 */
export type UserActivity = $ModelResult<$Schema, "UserActivity">;
/**
 * AppKit / Reown configuration (singleton per deployment)
 */
export type AppKitConfig = $ModelResult<$Schema, "AppKitConfig">;
/**
 * Central user — one record for every role in the system
 */
export type User = $ModelResult<$Schema, "User">;
/**
 * Profile questionnaire submission (POST /api/profile). One per user; upserted on save.
 */
export type UserProfileSetup = $ModelResult<$Schema, "UserProfileSetup">;
/**
 * Site-wide settings (replaces site-settings-store Blob). Key-value; e.g. marketplaceUrl.
 */
export type SiteSetting = $ModelResult<$Schema, "SiteSetting">;
/**
 * Feedback / analytics events (replaces feedback-store Blob). e.g. experience_hire_bike.
 */
export type Feedback = $ModelResult<$Schema, "Feedback">;
/**
 * Platform media assets (blob URLs) for admin/venue host to choose from when setting entity images.
 */
export type PlatformMediaAsset = $ModelResult<$Schema, "PlatformMediaAsset">;
/**
 * User membership / subscription (replaces membership-store Blob). Tier: essential | pro | event_organizer | elite.
 */
export type Subscription = $ModelResult<$Schema, "Subscription">;
/**
 * Partnership agreement (replaces agreement data in users-store Blob).
 */
export type PartnershipAgreement = $ModelResult<$Schema, "PartnershipAgreement">;
/**
 * Role-specific agreement (Event Organizer, Promoter, Influencer). Must be signed before purchasing the corresponding membership tier.
 */
export type RoleAgreement = $ModelResult<$Schema, "RoleAgreement">;
/**
 * Admin 6-digit verification code (replaces admin-codes-store Blob). Short-lived; consume = delete.
 */
export type AdminVerificationCode = $ModelResult<$Schema, "AdminVerificationCode">;
/**
 * Revoked JWT/session IDs (replaces revoked-sessions-store Blob). Prune expired on read or cron.
 */
export type RevokedSession = $ModelResult<$Schema, "RevokedSession">;
/**
 * A magic link generated by a promoter and targeted at a specific person
 * (influencer, VIP guest, high-value contact).
 */
export type PromoterMagicLink = $ModelResult<$Schema, "PromoterMagicLink">;
/**
 * Every time someone clicks a magic link — anonymous until they register
 */
export type MagicLinkClickEvent = $ModelResult<$Schema, "MagicLinkClickEvent">;
export type PromoterLinkBroadcast = $ModelResult<$Schema, "PromoterLinkBroadcast">;
/**
 * Onboarding journey — captures each step a magic-link user takes
 * from first click through registration to first purchase
 */
export type OnboardingJourney = $ModelResult<$Schema, "OnboardingJourney">;
export type MemberProfile = $ModelResult<$Schema, "MemberProfile">;
export type MemberFavorite = $ModelResult<$Schema, "MemberFavorite">;
export type VenueProfile = $ModelResult<$Schema, "VenueProfile">;
export type VenueStaff = $ModelResult<$Schema, "VenueStaff">;
export type VenueTable = $ModelResult<$Schema, "VenueTable">;
export type VenueTableAvailability = $ModelResult<$Schema, "VenueTableAvailability">;
export type VenueAvailability = $ModelResult<$Schema, "VenueAvailability">;
export type VenueEvent = $ModelResult<$Schema, "VenueEvent">;
export type VenueTicket = $ModelResult<$Schema, "VenueTicket">;
export type VenueAnnouncement = $ModelResult<$Schema, "VenueAnnouncement">;
export type HostProfile = $ModelResult<$Schema, "HostProfile">;
export type HostPhoto = $ModelResult<$Schema, "HostPhoto">;
export type HostAvailability = $ModelResult<$Schema, "HostAvailability">;
export type VenueHostAssignment = $ModelResult<$Schema, "VenueHostAssignment">;
export type HostBooking = $ModelResult<$Schema, "HostBooking">;
export type HostEarnings = $ModelResult<$Schema, "HostEarnings">;
export type HostPayout = $ModelResult<$Schema, "HostPayout">;
/**
 * Promoter commission split configuration per tier
 * (seeded from platform defaults; overridable per promoter by PLATFORM_ADMIN)
 */
export type CommissionSplitConfig = $ModelResult<$Schema, "CommissionSplitConfig">;
export type PromoterProfile = $ModelResult<$Schema, "PromoterProfile">;
/**
 * Tracks promoter attribution conflicts and member preference resolution
 * CRITICAL: Unique constraint prevents race-condition duplicates
 * CRITICAL: Member-scoped access policies prevent cross-tenant data leakage
 */
export type MemberPromoterPreference = $ModelResult<$Schema, "MemberPromoterPreference">;
/**
 * Junction model for venue nomination of promoters for specific events
 * Prevents unauthorized link generation for non-nominated events
 */
export type VenueEventPromoter = $ModelResult<$Schema, "VenueEventPromoter">;
/**
 * Promoter social channel configuration for broadcast functionality
 */
export type PromoterSocialChannel = $ModelResult<$Schema, "PromoterSocialChannel">;
export type PromoterReferral = $ModelResult<$Schema, "PromoterReferral">;
/**
 * One commission record per booking that used a promoter referral
 */
export type PromoterCommission = $ModelResult<$Schema, "PromoterCommission">;
export type PromoterMilestone = $ModelResult<$Schema, "PromoterMilestone">;
/**
 * Core analytical model storing pre-computed performance metrics per promoter per venue
 * MEDIUM: isStale field added for batch job compatibility
 */
export type PromoterVenuePerformance = $ModelResult<$Schema, "PromoterVenuePerformance">;
/**
 * Time-series record capturing promoter performance per event
 */
export type PromoterPerformanceSnapshot = $ModelResult<$Schema, "PromoterPerformanceSnapshot">;
/**
 * Venue admin custom dimension weights for composite scoring
 */
export type VenuePromoterWeightConfig = $ModelResult<$Schema, "VenuePromoterWeightConfig">;
export type PromoCode = $ModelResult<$Schema, "PromoCode">;
export type VenuePromotion = $ModelResult<$Schema, "VenuePromotion">;
export type Booking = $ModelResult<$Schema, "Booking">;
export type BookingAddOn = $ModelResult<$Schema, "BookingAddOn">;
export type BookingPayment = $ModelResult<$Schema, "BookingPayment">;
export type BookingActivity = $ModelResult<$Schema, "BookingActivity">;
export type VipArrivalAlert = $ModelResult<$Schema, "VipArrivalAlert">;
/**
 * Platform-level Stripe configuration (singleton)
 */
export type StripeConfig = $ModelResult<$Schema, "StripeConfig">;
/**
 * Stripe Connect account for venues, promoters, and hosts
 * (enables direct payouts from platform to these parties)
 */
export type StripeConnectedAccount = $ModelResult<$Schema, "StripeConnectedAccount">;
/**
 * Stripe customer record for members (stores payment methods)
 */
export type StripeCustomerRecord = $ModelResult<$Schema, "StripeCustomerRecord">;
/**
 * Transfer from platform to a connected account (venue, promoter, host payout)
 */
export type StripeTransfer = $ModelResult<$Schema, "StripeTransfer">;
/**
 * Stripe webhook event log — ensures idempotent processing
 */
export type StripeWebhookEvent = $ModelResult<$Schema, "StripeWebhookEvent">;
/**
 * Blockchain network configuration
 */
export type BlockchainNetworkConfig = $ModelResult<$Schema, "BlockchainNetworkConfig">;
/**
 * Deployed smart contract registry
 */
export type SmartContract = $ModelResult<$Schema, "SmartContract">;
/**
 * On-chain transaction record
 */
export type BlockchainTransaction = $ModelResult<$Schema, "BlockchainTransaction">;
export type PrestixWallet = $ModelResult<$Schema, "PrestixWallet">;
export type WalletTransaction = $ModelResult<$Schema, "WalletTransaction">;
export type WalletWithdrawal = $ModelResult<$Schema, "WalletWithdrawal">;
/**
 * Periodic venue settlement (87.5% net of gross bookings)
 */
export type VenueSettlement = $ModelResult<$Schema, "VenueSettlement">;
/**
 * Chart of Accounts — reference table
 */
export type ChartOfAccount = $ModelResult<$Schema, "ChartOfAccount">;
/**
 * Double-entry journal entry — every debit has a matching credit
 */
export type LedgerEntry = $ModelResult<$Schema, "LedgerEntry">;
/**
 * Monthly/quarterly accounting period — controls when ledger is closed
 */
export type AccountingPeriod = $ModelResult<$Schema, "AccountingPeriod">;
/**
 * Tax configuration per jurisdiction
 */
export type TaxConfiguration = $ModelResult<$Schema, "TaxConfiguration">;
/**
 * Individual tax record per taxable transaction
 */
export type TaxRecord = $ModelResult<$Schema, "TaxRecord">;
/**
 * Generated financial reports (PDF / JSON)
 */
export type FinancialReport = $ModelResult<$Schema, "FinancialReport">;
/**
 * Platform-level revenue summary (for accounting dashboard)
 */
export type PlatformRevenueRecord = $ModelResult<$Schema, "PlatformRevenueRecord">;
export type VenueReview = $ModelResult<$Schema, "VenueReview">;
export type HostReview = $ModelResult<$Schema, "HostReview">;
export type Notification = $ModelResult<$Schema, "Notification">;
export type ContentReport = $ModelResult<$Schema, "ContentReport">;
export type ModerationAction = $ModelResult<$Schema, "ModerationAction">;
export type SupportTicket = $ModelResult<$Schema, "SupportTicket">;
export type SupportMessage = $ModelResult<$Schema, "SupportMessage">;
export type BookingDispute = $ModelResult<$Schema, "BookingDispute">;
export type VenueDailyMetrics = $ModelResult<$Schema, "VenueDailyMetrics">;
export type PromoterDailyMetrics = $ModelResult<$Schema, "PromoterDailyMetrics">;
export type PlatformDailyMetrics = $ModelResult<$Schema, "PlatformDailyMetrics">;
/**
 * Long-running agent conversation session (voice, text, or headless).
 */
export type AgentSession = $ModelResult<$Schema, "AgentSession">;
/**
 * Single exchange within an agent session: input → provider → output.
 */
export type AgentConversationSegment = $ModelResult<$Schema, "AgentConversationSegment">;
/**
 * Reusable multi-step procedure learned by the agent from successful executions.
 */
export type AgentProcedure = $ModelResult<$Schema, "AgentProcedure">;
/**
 * Persistent learning memory — corrections, glossary terms, style rules, and
 * semantic embeddings. Replaces the flat JSON file `data/interpreter-learning.json`.
 */
export type LearningMemory = $ModelResult<$Schema, "LearningMemory">;
export type AuditLog = $ModelResult<$Schema, "AuditLog">;
export const PrestixUserRole = $schema.enums.PrestixUserRole.values;
export type PrestixUserRole = (typeof PrestixUserRole)[keyof typeof PrestixUserRole];
export const UserStatus = $schema.enums.UserStatus.values;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];
export const MembershipTier = $schema.enums.MembershipTier.values;
export type MembershipTier = (typeof MembershipTier)[keyof typeof MembershipTier];
export const VenueType = $schema.enums.VenueType.values;
export type VenueType = (typeof VenueType)[keyof typeof VenueType];
export const VenueStatus = $schema.enums.VenueStatus.values;
export type VenueStatus = (typeof VenueStatus)[keyof typeof VenueStatus];
export const TableType = $schema.enums.TableType.values;
export type TableType = (typeof TableType)[keyof typeof TableType];
export const TableStatus = $schema.enums.TableStatus.values;
export type TableStatus = (typeof TableStatus)[keyof typeof TableStatus];
export const BookingType = $schema.enums.BookingType.values;
export type BookingType = (typeof BookingType)[keyof typeof BookingType];
export const BookingStatus = $schema.enums.BookingStatus.values;
export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];
export const PaymentRail = $schema.enums.PaymentRail.values;
export type PaymentRail = (typeof PaymentRail)[keyof typeof PaymentRail];
export const PaymentStatus = $schema.enums.PaymentStatus.values;
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
export const HostStatus = $schema.enums.HostStatus.values;
export type HostStatus = (typeof HostStatus)[keyof typeof HostStatus];
export const PromoterStatus = $schema.enums.PromoterStatus.values;
export type PromoterStatus = (typeof PromoterStatus)[keyof typeof PromoterStatus];
export const PromoterTier = $schema.enums.PromoterTier.values;
export type PromoterTier = (typeof PromoterTier)[keyof typeof PromoterTier];
export const PromoterBindingScope = $schema.enums.PromoterBindingScope.values;
export type PromoterBindingScope = (typeof PromoterBindingScope)[keyof typeof PromoterBindingScope];
export const MemberPreferenceStatus = $schema.enums.MemberPreferenceStatus.values;
export type MemberPreferenceStatus = (typeof MemberPreferenceStatus)[keyof typeof MemberPreferenceStatus];
export const PromoterPerformanceDimension = $schema.enums.PromoterPerformanceDimension.values;
export type PromoterPerformanceDimension = (typeof PromoterPerformanceDimension)[keyof typeof PromoterPerformanceDimension];
export const VenueEventPromoterStatus = $schema.enums.VenueEventPromoterStatus.values;
export type VenueEventPromoterStatus = (typeof VenueEventPromoterStatus)[keyof typeof VenueEventPromoterStatus];
export const SocialChannelPlatform = $schema.enums.SocialChannelPlatform.values;
export type SocialChannelPlatform = (typeof SocialChannelPlatform)[keyof typeof SocialChannelPlatform];
export const WalletTransactionType = $schema.enums.WalletTransactionType.values;
export type WalletTransactionType = (typeof WalletTransactionType)[keyof typeof WalletTransactionType];
export const WalletStatus = $schema.enums.WalletStatus.values;
export type WalletStatus = (typeof WalletStatus)[keyof typeof WalletStatus];
export const WithdrawalStatus = $schema.enums.WithdrawalStatus.values;
export type WithdrawalStatus = (typeof WithdrawalStatus)[keyof typeof WithdrawalStatus];
export const SettlementStatus = $schema.enums.SettlementStatus.values;
export type SettlementStatus = (typeof SettlementStatus)[keyof typeof SettlementStatus];
export const StripeAccountStatus = $schema.enums.StripeAccountStatus.values;
export type StripeAccountStatus = (typeof StripeAccountStatus)[keyof typeof StripeAccountStatus];
export const StripePayoutStatus = $schema.enums.StripePayoutStatus.values;
export type StripePayoutStatus = (typeof StripePayoutStatus)[keyof typeof StripePayoutStatus];
export const StripeWebhookStatus = $schema.enums.StripeWebhookStatus.values;
export type StripeWebhookStatus = (typeof StripeWebhookStatus)[keyof typeof StripeWebhookStatus];
export const BlockchainNetwork = $schema.enums.BlockchainNetwork.values;
export type BlockchainNetwork = (typeof BlockchainNetwork)[keyof typeof BlockchainNetwork];
export const ContractType = $schema.enums.ContractType.values;
export type ContractType = (typeof ContractType)[keyof typeof ContractType];
export const OnChainTxStatus = $schema.enums.OnChainTxStatus.values;
export type OnChainTxStatus = (typeof OnChainTxStatus)[keyof typeof OnChainTxStatus];
export const LedgerEntryType = $schema.enums.LedgerEntryType.values;
export type LedgerEntryType = (typeof LedgerEntryType)[keyof typeof LedgerEntryType];
export const AccountCode = $schema.enums.AccountCode.values;
export type AccountCode = (typeof AccountCode)[keyof typeof AccountCode];
export const TaxType = $schema.enums.TaxType.values;
export type TaxType = (typeof TaxType)[keyof typeof TaxType];
export const ReportType = $schema.enums.ReportType.values;
export type ReportType = (typeof ReportType)[keyof typeof ReportType];
export const ReportStatus = $schema.enums.ReportStatus.values;
export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];
export const NotificationType = $schema.enums.NotificationType.values;
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];
export const NotificationChannel = $schema.enums.NotificationChannel.values;
export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel];
export const NotificationStatus = $schema.enums.NotificationStatus.values;
export type NotificationStatus = (typeof NotificationStatus)[keyof typeof NotificationStatus];
export const DisputeStatus = $schema.enums.DisputeStatus.values;
export type DisputeStatus = (typeof DisputeStatus)[keyof typeof DisputeStatus];
export const ContentReportStatus = $schema.enums.ContentReportStatus.values;
export type ContentReportStatus = (typeof ContentReportStatus)[keyof typeof ContentReportStatus];
export const ModerationActionType = $schema.enums.ModerationActionType.values;
export type ModerationActionType = (typeof ModerationActionType)[keyof typeof ModerationActionType];
export const TicketStatus = $schema.enums.TicketStatus.values;
export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus];
