/**
 * Enhanced Navigation Generator
 * Auto-detects all admin endpoints and generates comprehensive navigation structure
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

interface NavigationItem {
  id: string;
  title: string;
  href: string;
  icon?: string;
  authRequired?: boolean;
  description?: string;
  badge?: string;
  category?: string;
  children?: NavigationItem[];
}

interface EntityMapping {
  name: string;
  route: string;
  category: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  icon: string;
  parentEntity?: string;
  isAutoGenerated: boolean;
  description: string;
}

export class EnhancedNavigationGenerator {
  private readonly configPath = 'src/config/app.ts';
  private readonly adminDir = 'src/app/admin';
  
  // Entity categorization and icon mapping - Comprehensive list of all admin endpoints
  private readonly entityConfig: Record<string, EntityMapping> = {
    // TOKENIZATION & BLOCKCHAIN
    'token-management': { name: 'Token Management', route: '/admin/token-management', category: 'tokenization', priority: 'critical', icon: 'coins', isAutoGenerated: false, description: 'Token operations and management' },
    'token-onboarding': { name: 'Token Onboarding', route: '/admin/token-onboarding', category: 'tokenization', priority: 'high', icon: 'rocket', isAutoGenerated: false, description: 'Token onboarding flow' },
    'tokenHolder': { name: 'Token Holders', route: '/admin/tokenHolder', category: 'tokenization', priority: 'high', icon: 'users', isAutoGenerated: true, description: 'Token ownership tracking' },
    'tokenMintEvent': { name: 'Token Mint Events', route: '/admin/tokenMintEvent', category: 'tokenization', priority: 'medium', icon: 'sparkles', isAutoGenerated: true, parentEntity: 'tokenHolder', description: 'Token minting events' },
    'tokenOnboarding': { name: 'Token Onboarding Records', route: '/admin/tokenOnboarding', category: 'tokenization', priority: 'medium', icon: 'arrow-right', isAutoGenerated: true, description: 'Token onboarding records' },
    'blockchain': { name: 'Blockchain', route: '/admin/blockchain', category: 'tokenization', priority: 'high', icon: 'link', isAutoGenerated: false, description: 'Blockchain operations' },
    'blockchainSync': { name: 'Blockchain Sync', route: '/admin/blockchainSync', category: 'tokenization', priority: 'high', icon: 'refresh-cw', isAutoGenerated: false, description: 'Blockchain synchronization' },
    'blockchainNetwork': { name: 'Blockchain Networks', route: '/admin/blockchainNetwork', category: 'tokenization', priority: 'medium', icon: 'network', isAutoGenerated: true, description: 'Network configuration' },
    'smartContract': { name: 'Smart Contracts', route: '/admin/smartContract', category: 'tokenization', priority: 'high', icon: 'file-code', isAutoGenerated: false, description: 'Smart contract management' },
    'deployedContract': { name: 'Deployed Contracts', route: '/admin/deployedContract', category: 'tokenization', priority: 'medium', icon: 'package', isAutoGenerated: true, description: 'Deployed contract records' },
    'contractState': { name: 'Contract States', route: '/admin/contractState', category: 'tokenization', priority: 'low', icon: 'circle-dot', isAutoGenerated: true, description: 'Contract state tracking' },
    'contractUpgrade': { name: 'Contract Upgrades', route: '/admin/contractUpgrade', category: 'tokenization', priority: 'low', icon: 'arrow-up', isAutoGenerated: true, description: 'Contract upgrade history' },
    'contractDependency': { name: 'Contract Dependencies', route: '/admin/contractDependency', category: 'tokenization', priority: 'low', icon: 'git-branch', isAutoGenerated: true, description: 'Contract dependencies' },
    'contractMetrics': { name: 'Contract Metrics', route: '/admin/contractMetrics', category: 'tokenization', priority: 'low', icon: 'bar-chart', isAutoGenerated: true, description: 'Contract performance metrics' },
    'contractAdminRole': { name: 'Contract Admin Roles', route: '/admin/contractAdminRole', category: 'tokenization', priority: 'low', icon: 'shield', isAutoGenerated: true, description: 'Contract administration roles' },
    'rpcProvider': { name: 'RPC Providers', route: '/admin/rpcProvider', category: 'tokenization', priority: 'low', icon: 'server', isAutoGenerated: true, description: 'RPC provider configuration' },
    
    // INVESTMENT MANAGEMENT
    'investment': { name: 'Investments', route: '/admin/investment', category: 'investment', priority: 'high', icon: 'trending-up', isAutoGenerated: true, description: 'Investment records' },
    'investmentPerformance': { name: 'Investment Performance', route: '/admin/investmentPerformance', category: 'investment', priority: 'medium', icon: 'line-chart', isAutoGenerated: true, parentEntity: 'investment', description: 'Investment performance tracking' },
    'investmentBenchmark': { name: 'Investment Benchmarks', route: '/admin/investmentBenchmark', category: 'investment', priority: 'medium', icon: 'target', isAutoGenerated: true, parentEntity: 'investment', description: 'Investment benchmark data' },
    'investmentRisk': { name: 'Investment Risk', route: '/admin/investmentRisk', category: 'investment', priority: 'medium', icon: 'alert-triangle', isAutoGenerated: true, parentEntity: 'investment', description: 'Investment risk analysis' },
    'investmentGamingTransfer': { name: 'Gaming Transfers', route: '/admin/investmentGamingTransfer', category: 'investment', priority: 'medium', icon: 'gamepad-2', isAutoGenerated: true, parentEntity: 'investment', description: 'Gaming transfer records' },
    'portfolio': { name: 'Portfolios', route: '/admin/portfolio', category: 'investment', priority: 'high', icon: 'briefcase', isAutoGenerated: true, description: 'Investor portfolios' },
    'portfolioAnalysis': { name: 'Portfolio Analysis', route: '/admin/portfolioAnalysis', category: 'investment', priority: 'medium', icon: 'pie-chart', isAutoGenerated: true, parentEntity: 'portfolio', description: 'Portfolio analysis reports' },
    'deposit': { name: 'Deposits', route: '/admin/deposit', category: 'investment', priority: 'high', icon: 'arrow-down-circle', isAutoGenerated: true, description: 'Deposit records' },
    'monthlyReturn': { name: 'Monthly Returns', route: '/admin/monthlyReturn', category: 'investment', priority: 'medium', icon: 'calendar', isAutoGenerated: true, parentEntity: 'investment', description: 'Monthly return calculations' },
    'financialMetrics': { name: 'Financial Metrics', route: '/admin/financialMetrics', category: 'investment', priority: 'medium', icon: 'dollar-sign', isAutoGenerated: true, parentEntity: 'properties', description: 'Property financial metrics' },
    'cashFlowProjection': { name: 'Cash Flow Projections', route: '/admin/cashFlowProjection', category: 'investment', priority: 'medium', icon: 'trending-up', isAutoGenerated: true, parentEntity: 'properties', description: 'Cash flow projections' },
    'marketComparable': { name: 'Market Comparables', route: '/admin/marketComparable', category: 'investment', priority: 'medium', icon: 'layers', isAutoGenerated: true, parentEntity: 'properties', description: 'Market comparable properties' },
    'marketIntelligence': { name: 'Market Intelligence', route: '/admin/marketIntelligence', category: 'investment', priority: 'medium', icon: 'brain', isAutoGenerated: true, description: 'Market intelligence data' },
    
    // PROPERTY MANAGEMENT
    'properties': { name: 'Properties', route: '/admin/properties', category: 'property', priority: 'critical', icon: 'building', isAutoGenerated: false, description: 'Property listings' },
    'propertyLocation': { name: 'Property Locations', route: '/admin/propertyLocation', category: 'property', priority: 'medium', icon: 'map-pin', isAutoGenerated: true, parentEntity: 'properties', description: 'Property location data' },
    'propertyImage': { name: 'Property Images', route: '/admin/propertyImage', category: 'property', priority: 'medium', icon: 'image', isAutoGenerated: true, parentEntity: 'properties', description: 'Property image gallery' },
    'propertyOnboarding': { name: 'Property Onboarding', route: '/admin/propertyOnboarding', category: 'property', priority: 'medium', icon: 'file-plus', isAutoGenerated: true, parentEntity: 'properties', description: 'Property onboarding records' },
    'propertyCashFlow': { name: 'Property Cash Flows', route: '/admin/propertyCashFlow', category: 'property', priority: 'medium', icon: 'flow', isAutoGenerated: true, parentEntity: 'properties', description: 'Property cash flow data' },
    'propertyExpense': { name: 'Property Expenses', route: '/admin/propertyExpense', category: 'property', priority: 'medium', icon: 'receipt', isAutoGenerated: true, parentEntity: 'properties', description: 'Property expense records' },
    'propertyRental': { name: 'Property Rentals', route: '/admin/propertyRental', category: 'property', priority: 'medium', icon: 'home', isAutoGenerated: true, parentEntity: 'properties', description: 'Property rental data' },
    'propertyValuation': { name: 'Property Valuations', route: '/admin/propertyValuation', category: 'property', priority: 'medium', icon: 'calculator', isAutoGenerated: true, parentEntity: 'properties', description: 'Property valuation records' },
    
    // USER MANAGEMENT
    'user': { name: 'Users', route: '/admin/user', category: 'user', priority: 'critical', icon: 'user', isAutoGenerated: true, description: 'User account management' },
    'userSettings': { name: 'User Settings', route: '/admin/userSettings', category: 'user', priority: 'high', icon: 'settings', isAutoGenerated: false, description: 'User preferences' },
    'userPreferences': { name: 'User Preferences', route: '/admin/userPreferences', category: 'user', priority: 'medium', icon: 'sliders', isAutoGenerated: true, parentEntity: 'user', description: 'User preference records' },
    'userActivity': { name: 'User Activity', route: '/admin/userActivity', category: 'user', priority: 'medium', icon: 'activity', isAutoGenerated: true, parentEntity: 'user', description: 'User activity logs' },
    'userEngagementMetrics': { name: 'User Engagement Metrics', route: '/admin/userEngagementMetrics', category: 'user', priority: 'medium', icon: 'trending-up', isAutoGenerated: true, parentEntity: 'user', description: 'User engagement analytics' },
    'userQtechAccount': { name: 'User QTech Accounts', route: '/admin/userQtechAccount', category: 'user', priority: 'medium', icon: 'gamepad-2', isAutoGenerated: true, parentEntity: 'user', description: 'QTech account mappings' },
    'userPamMapping': { name: 'User PAM Mappings', route: '/admin/userPamMapping', category: 'user', priority: 'medium', icon: 'link', isAutoGenerated: true, parentEntity: 'user', description: 'PAM system mappings' },
    'walletSession': { name: 'Wallet Sessions', route: '/admin/walletSession', category: 'user', priority: 'high', icon: 'wallet', isAutoGenerated: true, description: 'Wallet authentication sessions' },
    'walletConnection': { name: 'Wallet Connections', route: '/admin/walletConnection', category: 'user', priority: 'medium', icon: 'plug', isAutoGenerated: true, parentEntity: 'walletSession', description: 'Wallet connection records' },
    'walletTransaction': { name: 'Wallet Transactions', route: '/admin/walletTransaction', category: 'user', priority: 'medium', icon: 'credit-card', isAutoGenerated: true, parentEntity: 'walletSession', description: 'Wallet transaction history' },
    'account': { name: 'Accounts', route: '/admin/account', category: 'user', priority: 'high', icon: 'user-circle', isAutoGenerated: true, parentEntity: 'user', description: 'User account records' },
    
    // GAMING INTEGRATION
    'tokenizin-games': { name: 'Tiger Games', route: '/admin/tokenizin-games', category: 'gaming', priority: 'medium', icon: 'gamepad', isAutoGenerated: false, description: 'Tiger Games management' },
    'pam-integration': { name: 'PAM Integration', route: '/admin/pam-integration', category: 'gaming', priority: 'medium', icon: 'link', isAutoGenerated: false, description: 'PAM system integration' },
    'qtechGame': { name: 'QTech Games', route: '/admin/qtechGame', category: 'gaming', priority: 'high', icon: 'joystick', isAutoGenerated: true, description: 'QTech gaming platform' },
    'qtechGameRound': { name: 'QTech Game Rounds', route: '/admin/qtechGameRound', category: 'gaming', priority: 'medium', icon: 'circle', isAutoGenerated: true, parentEntity: 'qtechGame', description: 'Game round records' },
    'qtechTransaction': { name: 'QTech Transactions', route: '/admin/qtechTransaction', category: 'gaming', priority: 'high', icon: 'repeat', isAutoGenerated: true, parentEntity: 'qtechGame', description: 'QTech transaction records' },
    'qtechErrorLog': { name: 'QTech Error Logs', route: '/admin/qtechErrorLog', category: 'gaming', priority: 'medium', icon: 'alert-circle', isAutoGenerated: true, description: 'QTech error tracking' },
    'qtechProvider': { name: 'QTech Providers', route: '/admin/qtechProvider', category: 'gaming', priority: 'medium', icon: 'server', isAutoGenerated: true, description: 'QTech provider configuration' },
    'qtechNGRAggregation': { name: 'QTech NGR Aggregations', route: '/admin/qtechNGRAggregation', category: 'gaming', priority: 'medium', icon: 'layers', isAutoGenerated: true, parentEntity: 'qtechGame', description: 'NGR aggregation data' },
    'gamingSession': { name: 'Gaming Sessions', route: '/admin/gamingSession', category: 'gaming', priority: 'medium', icon: 'play', isAutoGenerated: true, parentEntity: 'user', description: 'Gaming session records' },
    'pamTransaction': { name: 'PAM Transactions', route: '/admin/pamTransaction', category: 'gaming', priority: 'medium', icon: 'repeat', isAutoGenerated: true, parentEntity: 'user', description: 'PAM transaction records' },
    'pamErrorLog': { name: 'PAM Error Logs', route: '/admin/pamErrorLog', category: 'gaming', priority: 'medium', icon: 'alert-circle', isAutoGenerated: true, description: 'PAM error tracking' },
    'game': { name: 'Games', route: '/admin/game', category: 'gaming', priority: 'medium', icon: 'gamepad-2', isAutoGenerated: true, description: 'Game definitions' },
    'gameOperator': { name: 'Game Operators', route: '/admin/gameOperator', category: 'gaming', priority: 'medium', icon: 'users', isAutoGenerated: true, parentEntity: 'game', description: 'Game operator records' },
    'casinoTokenConfig': { name: 'Casino Token Config', route: '/admin/casinoTokenConfig', category: 'gaming', priority: 'medium', icon: 'coins', isAutoGenerated: true, description: 'Casino token configuration' },
    
    // CONTENT MANAGEMENT
    'blog': { name: 'Blog', route: '/admin/blog', category: 'content', priority: 'high', icon: 'file-text', isAutoGenerated: false, description: 'Blog management interface' },
    'blogPost': { name: 'Blog Posts', route: '/admin/blogPost', category: 'content', priority: 'high', icon: 'file-text', isAutoGenerated: true, description: 'Blog post management' },
    'blogPostLike': { name: 'Blog Post Likes', route: '/admin/blogPostLike', category: 'content', priority: 'low', icon: 'heart', isAutoGenerated: true, parentEntity: 'blogPost', description: 'Blog post likes' },
    'comment': { name: 'Comments', route: '/admin/comment', category: 'content', priority: 'medium', icon: 'message-square', isAutoGenerated: true, parentEntity: 'blogPost', description: 'Blog comments' },
    'savedPost': { name: 'Saved Posts', route: '/admin/savedPost', category: 'content', priority: 'low', icon: 'bookmark', isAutoGenerated: true, parentEntity: 'blogPost', description: 'User saved posts' },
    'notification': { name: 'Notifications', route: '/admin/notification', category: 'content', priority: 'high', icon: 'bell', isAutoGenerated: true, description: 'System notifications' },
    'notificationTemplate': { name: 'Notification Templates', route: '/admin/notificationTemplate', category: 'content', priority: 'medium', icon: 'mail', isAutoGenerated: true, description: 'Notification templates' },
    'conversation': { name: 'Conversations', route: '/admin/conversation', category: 'content', priority: 'medium', icon: 'message-circle', isAutoGenerated: true, description: 'User conversations' },
    'conversationMessage': { name: 'Conversation Messages', route: '/admin/conversationMessage', category: 'content', priority: 'medium', icon: 'message-square', isAutoGenerated: true, parentEntity: 'conversation', description: 'Conversation messages' },
    'chatSession': { name: 'Chat Sessions', route: '/admin/chatSession', category: 'content', priority: 'medium', icon: 'message-circle', isAutoGenerated: true, parentEntity: 'user', description: 'Chat session records' },
    'chatMessage': { name: 'Chat Messages', route: '/admin/chatMessage', category: 'content', priority: 'medium', icon: 'message-square', isAutoGenerated: true, parentEntity: 'chatSession', description: 'Chat message records' },
    'aIInteraction': { name: 'AI Interactions', route: '/admin/aIInteraction', category: 'content', priority: 'medium', icon: 'brain', isAutoGenerated: true, parentEntity: 'user', description: 'AI interaction logs' },
    
    // COMPLIANCE & DUE DILIGENCE
    'auditLog': { name: 'Audit Logs', route: '/admin/auditLog', category: 'compliance', priority: 'high', icon: 'file-search', isAutoGenerated: true, description: 'Security audit logs' },
    'document': { name: 'Documents', route: '/admin/document', category: 'compliance', priority: 'high', icon: 'file-text', isAutoGenerated: true, parentEntity: 'properties', description: 'Property documents' },
    'documentation': { name: 'Documentation', route: '/admin/documentation', category: 'compliance', priority: 'medium', icon: 'book', isAutoGenerated: true, description: 'System documentation' },
    'documentationVersion': { name: 'Documentation Versions', route: '/admin/documentationVersion', category: 'compliance', priority: 'medium', icon: 'git-branch', isAutoGenerated: true, parentEntity: 'documentation', description: 'Documentation version history' },
    'documentationConfig': { name: 'Documentation Config', route: '/admin/documentationConfig', category: 'compliance', priority: 'low', icon: 'settings', isAutoGenerated: true, description: 'Documentation configuration' },
    
    // E-COMMERCE
    'category': { name: 'Categories', route: '/admin/category', category: 'ecommerce', priority: 'high', icon: 'folder', isAutoGenerated: true, description: 'Product categories' },
    'product': { name: 'Products', route: '/admin/product', category: 'ecommerce', priority: 'high', icon: 'package', isAutoGenerated: true, description: 'Product management' },
    'productVariant': { name: 'Product Variants', route: '/admin/productVariant', category: 'ecommerce', priority: 'medium', icon: 'layers', isAutoGenerated: true, parentEntity: 'product', description: 'Product variant records' },
    'vendorProfile': { name: 'Vendor Profiles', route: '/admin/vendorProfile', category: 'ecommerce', priority: 'medium', icon: 'store', isAutoGenerated: true, parentEntity: 'user', description: 'Vendor profile records' },
    'order': { name: 'Orders', route: '/admin/order', category: 'ecommerce', priority: 'high', icon: 'shopping-cart', isAutoGenerated: true, description: 'Order management' },
    'orderItem': { name: 'Order Items', route: '/admin/orderItem', category: 'ecommerce', priority: 'medium', icon: 'list', isAutoGenerated: true, parentEntity: 'order', description: 'Order item records' },
    'payment': { name: 'Payments', route: '/admin/payment', category: 'ecommerce', priority: 'high', icon: 'credit-card', isAutoGenerated: true, parentEntity: 'order', description: 'Payment records' },
    'cart': { name: 'Carts', route: '/admin/cart', category: 'ecommerce', priority: 'low', icon: 'shopping-bag', isAutoGenerated: true, parentEntity: 'user', description: 'Shopping cart records' },
    'cartItem': { name: 'Cart Items', route: '/admin/cartItem', category: 'ecommerce', priority: 'low', icon: 'list', isAutoGenerated: true, parentEntity: 'cart', description: 'Cart item records' },
    'wishlistItem': { name: 'Wishlist Items', route: '/admin/wishlistItem', category: 'ecommerce', priority: 'low', icon: 'heart', isAutoGenerated: true, parentEntity: 'user', description: 'Wishlist records' },
    'review': { name: 'Reviews', route: '/admin/review', category: 'ecommerce', priority: 'medium', icon: 'star', isAutoGenerated: true, parentEntity: 'product', description: 'Product reviews' },
    
    // PAYMENTS
    'stripePayment': { name: 'Stripe Payments', route: '/admin/stripePayment', category: 'payments', priority: 'high', icon: 'credit-card', isAutoGenerated: true, parentEntity: 'properties', description: 'Stripe payment records' },
    'stripeProduct': { name: 'Stripe Products', route: '/admin/stripeProduct', category: 'payments', priority: 'medium', icon: 'package', isAutoGenerated: true, description: 'Stripe product records' },
    'stripePrice': { name: 'Stripe Prices', route: '/admin/stripePrice', category: 'payments', priority: 'medium', icon: 'dollar-sign', isAutoGenerated: true, parentEntity: 'stripeProduct', description: 'Stripe price records' },
    'subscription': { name: 'Subscriptions', route: '/admin/subscription', category: 'payments', priority: 'high', icon: 'repeat', isAutoGenerated: true, parentEntity: 'user', description: 'User subscriptions' },
    'price': { name: 'Prices', route: '/admin/price', category: 'payments', priority: 'medium', icon: 'tag', isAutoGenerated: true, parentEntity: 'stripeProduct', description: 'Price records' },
    'customer': { name: 'Customers', route: '/admin/customer', category: 'payments', priority: 'medium', icon: 'users', isAutoGenerated: true, parentEntity: 'user', description: 'Customer records' },
    
    // SYSTEM ADMINISTRATION
    'database': { name: 'Database Explorer', route: '/admin/database', category: 'system', priority: 'critical', icon: 'database', isAutoGenerated: false, description: 'Database management interface' },
    'analytics': { name: 'Analytics', route: '/admin/analytics', category: 'system', priority: 'high', icon: 'bar-chart', isAutoGenerated: false, description: 'Platform analytics' },
    'tasks': { name: 'Tasks', route: '/admin/tasks', category: 'system', priority: 'medium', icon: 'check-square', isAutoGenerated: false, description: 'Task management' },
    'marketplace': { name: 'Marketplace', route: '/admin/marketplace', category: 'system', priority: 'high', icon: 'store', isAutoGenerated: false, description: 'Marketplace management' },
    'blobs': { name: 'Blobs', route: '/admin/blobs', category: 'system', priority: 'low', icon: 'image', isAutoGenerated: false, description: 'File storage management' },
    'enums': { name: 'Enums', route: '/admin/enums', category: 'system', priority: 'low', icon: 'list', isAutoGenerated: false, description: 'Enum management' },
    'settings': { name: 'Settings', route: '/admin/settings', category: 'system', priority: 'medium', icon: 'settings', isAutoGenerated: true, description: 'System settings' },
    'systemConfig': { name: 'System Config', route: '/admin/systemConfig', category: 'system', priority: 'medium', icon: 'settings', isAutoGenerated: true, description: 'System configuration' },
    'image': { name: 'Images', route: '/admin/image', category: 'system', priority: 'medium', icon: 'image', isAutoGenerated: true, description: 'Image management' },
    'imageUpload': { name: 'Image Uploads', route: '/admin/imageUpload', category: 'system', priority: 'medium', icon: 'upload', isAutoGenerated: true, description: 'Image upload records' },
  };

  /**
   * Scan admin directory for all endpoints
   */
  private scanAdminEndpoints(): string[] {
    const endpoints: string[] = [];
    
    if (!existsSync(this.adminDir)) {
      return endpoints;
    }

    const scanDirectory = (dir: string, basePath: string = '') => {
      const entries = readdirSync(dir, { withFileTypes: true });
      
      for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;
        
        if (entry.isDirectory()) {
          // Skip dynamic routes and special directories
          if (!entry.name.startsWith('[') && entry.name !== 'node_modules') {
            scanDirectory(fullPath, relativePath);
          }
        } else if (entry.name === 'page.tsx') {
          // Found a page endpoint
          const endpoint = relativePath.replace(/\/page\.tsx$/, '');
          endpoints.push(endpoint);
        }
      }
    };

    scanDirectory(this.adminDir);
    return endpoints;
  }

  /**
   * Generate navigation items from entity config
   */
  private generateNavigationItems(): NavigationItem[] {
    const items: NavigationItem[] = [];
    const categoryMap = new Map<string, NavigationItem[]>();

    // Group entities by category
    for (const [key, config] of Object.entries(this.entityConfig)) {
      const category = config.category;
      
      if (!categoryMap.has(category)) {
        categoryMap.set(category, []);
      }
      
      const navItem: NavigationItem = {
        id: `admin-${key}`,
        title: config.name,
        href: config.route,
        icon: config.icon,
        authRequired: true,
        description: config.description,
        badge: config.priority === 'critical' ? 'CRITICAL' : config.priority === 'high' ? 'HIGH' : undefined,
        category: 'admin',
      };

      categoryMap.get(category)!.push(navItem);
    }

    // Create category groupings
    const categoryTitles: Record<string, string> = {
      'tokenization': 'Tokenization & Blockchain',
      'investment': 'Investment Management',
      'property': 'Property Management',
      'user': 'User Management',
      'gaming': 'Gaming Integration',
      'content': 'Content Management',
      'compliance': 'Compliance & Due Diligence',
      'ecommerce': 'E-Commerce',
      'payments': 'Payments',
      'system': 'System Administration',
    };

    const categoryIcons: Record<string, string> = {
      'tokenization': 'coins',
      'investment': 'bar-chart',
      'property': 'building-2',
      'user': 'users',
      'gaming': 'gamepad-2',
      'content': 'edit',
      'compliance': 'shield-check',
      'ecommerce': 'shopping-bag',
      'payments': 'credit-card',
      'system': 'database',
    };

    // Build hierarchical structure
    for (const [category, entities] of categoryMap.entries()) {
      const categoryItem: NavigationItem = {
        id: `admin-${category}`,
        title: categoryTitles[category] || category.charAt(0).toUpperCase() + category.slice(1),
        href: '#',
        icon: categoryIcons[category] || 'folder',
        authRequired: true,
        description: `${categoryTitles[category] || category} operations`,
        category: 'admin',
        children: entities.sort((a, b) => {
          const priorityOrder: Record<string, number> = { 'critical': 0, 'high': 1, 'medium': 2, 'low': 3 };
          const aPriority = this.entityConfig[a.id.replace('admin-', '')]?.priority || 'low';
          const bPriority = this.entityConfig[b.id.replace('admin-', '')]?.priority || 'low';
          return priorityOrder[aPriority] - priorityOrder[bPriority];
        }),
      };

      items.push(categoryItem);
    }

    return items.sort((a, b) => {
      const categoryOrder = ['system', 'property', 'tokenization', 'investment', 'user', 'content', 'gaming', 'compliance', 'ecommerce', 'payments'];
      const aIndex = categoryOrder.indexOf(a.id.replace('admin-', ''));
      const bIndex = categoryOrder.indexOf(b.id.replace('admin-', ''));
      return (aIndex === -1 ? 999 : aIndex) - (bIndex === -1 ? 999 : bIndex);
    });
  }

  /**
   * Generate complete navigation configuration
   */
  async generate(): Promise<void> {
    console.log('🔧 Generating enhanced navigation configuration...');

    try {
      const navigationItems = this.generateNavigationItems();
      const scannedEndpoints = this.scanAdminEndpoints();
      
      console.log(`📊 Found ${scannedEndpoints.length} admin endpoints`);
      console.log(`📋 Generated ${navigationItems.length} navigation categories`);
      
      // Update config file
      await this.updateConfigFile(navigationItems);
      
      console.log('✅ Enhanced navigation generation completed successfully');
    } catch (error) {
      console.error('❌ Navigation generation failed:', error);
      throw error;
    }
  }

  /**
   * Update config file with new navigation
   */
  private async updateConfigFile(navigationItems: NavigationItem[]): Promise<void> {
    const configContent = readFileSync(this.configPath, 'utf-8');
    
    // Find and replace admin navigation section
    const adminNavStart = configContent.indexOf('// =====================\n    // ADMIN DASHBOARD');
    const adminNavEnd = configContent.indexOf('  ] as NavigationItem[],', adminNavStart);
    
    if (adminNavStart === -1 || adminNavEnd === -1) {
      throw new Error('Could not find admin navigation section in config file');
    }

    const beforeNav = configContent.substring(0, adminNavStart);
    const afterNav = configContent.substring(adminNavEnd);
    
    // Generate navigation code
    const navCode = this.generateNavCode(navigationItems);
    
    const newConfig = beforeNav + navCode + afterNav;
    
    writeFileSync(this.configPath, newConfig, 'utf-8');
    console.log('✅ Updated navigation configuration');
  }

  /**
   * Generate TypeScript code for navigation items
   */
  private generateNavCode(items: NavigationItem[]): string {
    const generateItem = (item: NavigationItem, indent: number = 4): string => {
      const indentStr = ' '.repeat(indent);
      const lines: string[] = [];
      
      lines.push(`${indentStr}{`);
      lines.push(`${indentStr}  id: "${item.id}",`);
      lines.push(`${indentStr}  title: "${item.title}",`);
      lines.push(`${indentStr}  href: "${item.href}",`);
      if (item.icon) {
        lines.push(`${indentStr}  icon: "${item.icon}",`);
      }
      if (item.authRequired !== undefined) {
        lines.push(`${indentStr}  authRequired: ${item.authRequired},`);
      }
      if (item.description) {
        lines.push(`${indentStr}  description: "${item.description}",`);
      }
      if (item.badge) {
        lines.push(`${indentStr}  badge: "${item.badge}",`);
      }
      if (item.category) {
        lines.push(`${indentStr}  category: "${item.category}",`);
      }
      if (item.children && item.children.length > 0) {
        lines.push(`${indentStr}  children: [`);
        item.children.forEach(child => {
          lines.push(generateItem(child, indent + 4));
          lines.push(`${indentStr}    },`);
        });
        lines.push(`${indentStr}  ],`);
      }
      lines.push(`${indentStr}},`);
      
      return lines.join('\n');
    };

    const lines: string[] = [];
    lines.push('    // =====================');
    lines.push('    // ADMIN DASHBOARD');
    lines.push('    // =====================');
    lines.push('    {');
    lines.push('      id: "admin-dashboard",');
    lines.push('      title: "Dashboard",');
    lines.push('      href: "/admin",');
    lines.push('      icon: "layout-dashboard",');
    lines.push('      authRequired: true,');
    lines.push('      description: "Admin overview and key metrics",');
    lines.push('      category: "admin",');
    lines.push('    },');
    lines.push('');
    
    items.forEach(item => {
      const itemCode = generateItem(item, 4);
      lines.push(itemCode);
      lines.push('');
    });

    return lines.join('\n');
  }
}

// Export for use in scripts
export default EnhancedNavigationGenerator;

