/**
 * Enhanced Form Generator
 * Generates forms with enhanced content editor integration
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import {
  ContentFieldConfig,
  getModelContentFields,
  shouldUseEnhancedContentEditor
} from './utils/content-field-detector';

export interface EnhancedFormConfig {
  modelName: string;
  fields: Array<{ name: string; type: string; isOptional: boolean; isEnum?: boolean; enumValues?: string[] }>;
  relations: Array<{ name: string; model: string; type: string; isOptional: boolean }>;
  contentFields: ContentFieldConfig[];
  hasEnhancedEditor: boolean;
  databaseFirst?: boolean;
}

export class EnhancedFormGenerator {
  private baseDir: string;
  private projectRoot: string = process.cwd();

  constructor(baseDir: string = 'src/generated') {
    this.baseDir = baseDir;
  }

  /**
   * Generate enhanced form component
   */
  generateEnhancedForm(config: EnhancedFormConfig): string {
    const { modelName, fields, relations, contentFields, hasEnhancedEditor, databaseFirst } = config;
    const lowerName = modelName.charAt(0).toLowerCase() + modelName.slice(1);
    
    // Check if specialized form store exists
    const specializedStorePath = `src/stores/form-stores/${lowerName}-form-store.ts`;
    const hasSpecializedStore = existsSync(join(this.projectRoot, specializedStorePath));
    
    // Get editable fields (exclude system fields)
    const editableFields = fields.filter(f => 
      !['id', 'createdAt', 'updatedAt', 'password'].includes(f.name)
    );
    
    // Get enum fields
    const enumFields = editableFields.filter(f => f.isEnum && f.enumValues);
    const enumImports = enumFields.length > 0
      ? `import { ${[...new Set(enumFields.map(f => f.type))].join(', ')}, getEnumValues, getEnumLabel } from '@/lib/enums';`
      : '';
    
    // Get mandatory relations
    const mandatoryRelations = relations.filter(r => !r.isOptional && r.type === 'many-to-one');
    const relationImports = mandatoryRelations.length > 0 
      ? `import { useQuery } from '@tanstack/react-query';`
      : '';

    // Generate content field names set
    const contentFieldNames = new Set(contentFields.map(f => f.fieldName));

    return `// Generated Enhanced Form Component for ${modelName}
// DO NOT EDIT - Auto-generated by EnhancedFormGenerator
${databaseFirst ? '// ⚠️ DATABASE-FIRST DATA POLICY ENFORCED' : ''}
// All data in this component MUST come from database queries, never hardcoded

'use client';

import React, { useEffect, useState } from 'react';
import { useCreate${modelName}, useUpdate${modelName} } from '@/generated/hooks/${lowerName}-hooks';
${relationImports}
${enumImports}
import type { ${modelName}, Create${modelName}Input, Update${modelName}Input } from '@/generated/types/${lowerName}-types';
${hasSpecializedStore ? `import { use${modelName}FormStore, type ${modelName}FormData } from '@/stores/form-stores/${lowerName}-form-store';` : 'import { useGeneratedFormStore } from \'@/stores/generated-form-store\';'}
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AdminImageField } from '@/components/admin/shared/AdminImageField';
import { AdminMultiImageField } from '@/components/admin/shared/AdminMultiImageField';
${hasEnhancedEditor ? "import { EnhancedContentEditor } from '@/components/admin/enhanced-content-editor';" : ''}
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { toast } from 'sonner';
import { useThemeStore } from '@/stores/ui-stores';

import { motion } from 'framer-motion';
import { 
  Loader2, 
  Save, 
  X, 
  FileText, 
  Image, 
  Settings, 
  Eye,
  Sparkles,
  Clock,
  CheckCircle2
} from 'lucide-react';

interface Enhanced${modelName}FormProps {
  mode: 'create' | 'edit';
  data?: ${modelName};
  onSuccess: () => void;
  onCancel: () => void;
}

// ✅ REDUX/ZUSTAND PATTERN - Default form data
const defaultFormData: any = {
${editableFields.map(field => {
  if (field.isEnum) {
    return `  ${field.name}: '',`;
  }
  if (field.type === 'Boolean') {
    return `  ${field.name}: false,`;
  }
  if (field.type === 'Int' || field.type === 'Float' || field.type === 'Decimal') {
    return `  ${field.name}: 0,`;
  }
  if (field.type === 'DateTime') {
    return `  ${field.name}: '',`;
  }
  return `  ${field.name}: '',`;
}).join('\n')}
};

export function Enhanced${modelName}Form({ mode, data, onSuccess, onCancel }: Enhanced${modelName}FormProps) {
  const [activeTab, setActiveTab] = useState('${hasEnhancedEditor ? 'content' : 'details'}');
  const [autoSaveStatus, setAutoSaveStatus] = useState<'idle' | 'saving' | 'saved'>('idle');
  
  // ✅ REDUX/ZUSTAND PATTERN - Use ${hasSpecializedStore ? 'Specialized' : 'Generated'} Form Store
  const {
    initializeForm,
    updateField,
    getFormData,
    submitForm,
    setFieldError,
    isFormDirty,
    destroyForm${hasSpecializedStore ? `,
    getFormErrors` : ''},
  } = ${hasSpecializedStore ? `use${modelName}FormStore()` : 'useGeneratedFormStore()'};
  
  const createMutation = useCreate${modelName}();
  const updateMutation = useUpdate${modelName}();
  
  // Generate unique form ID
  const formId = \`${lowerName}-enhanced-\${mode}-\${data?.id || 'new'}\`;

  // Fetch relation data from API endpoints
${mandatoryRelations.map(r => {
  const relModel = r.model;
  const relLower = relModel.charAt(0).toLowerCase() + relModel.slice(1);
  const apiEndpoint = `/api/${relLower}`;
  return `  const { data: ${relLower}Response, isLoading: ${relLower}Loading, error: ${relLower}Error } = useQuery({
    queryKey: ['${relLower}Options'],
    queryFn: async () => {
      const response = await fetch('${apiEndpoint}?pageSize=100', {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to fetch ${relModel} options');
      const result = await response.json();
      return Array.isArray(result.data) ? result.data : result.data || [];
    },
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  });
  const ${relLower}Options = ${relLower}Response || [];`;
}).join('\n')}

  // ✅ REDUX/ZUSTAND PATTERN - Single mount-time initialization
  useEffect(() => {
    // Prepare initial data
    let initialData: any;
    
    if (data && mode === 'edit') {
      initialData = {
${editableFields.map(field => {
  if (field.isEnum) {
    return `        ${field.name}: data.${field.name} ? String(data.${field.name}).toUpperCase() : '',`;
  }
  if (field.type === 'Int' || field.type === 'Float' || field.type === 'Decimal') {
    return `        ${field.name}: data.${field.name} ?? 0,`;
  }
  if (field.type === 'Boolean') {
    return `        ${field.name}: data.${field.name} ?? false,`;
  }
  if (field.type === 'DateTime') {
    return `        ${field.name}: data.${field.name} || '',`;
  }
  return `        ${field.name}: data.${field.name} || '',`;
}).join('\n')}
      };
    } else {
      initialData = defaultFormData;
    }
    
    ${hasSpecializedStore ? `initializeForm(formId, initialData);` : `initializeForm(formId, '${modelName}', mode, {}, initialData);`}
    
    return () => {
      // ✅ Cleanup - preserve dirty forms (drafts)
      if (!isFormDirty(formId)) {
        destroyForm(formId);
      }
    };
  }, []); // ✅ Empty deps - runs once on mount

  // ✅ REDUX/ZUSTAND PATTERN - Get form data from store
  const formData = getFormData(formId) ?? defaultFormData;
  const isSubmitting = createMutation.isPending || updateMutation.isPending;

  const handleChange = (field: ${hasSpecializedStore ? `keyof ${modelName}FormData` : 'string'}, value: any) => {
    updateField(formId, field, value);
  };

  // Auto-save functionality for content fields
  const handleAutoSave = async (field: string, content: string) => {
    if (mode !== 'edit' || !data?.id) return;
    
    setAutoSaveStatus('saving');
    try {
      await updateMutation.mutateAsync({
        id: data.id,
        [field]: content
      });
      setAutoSaveStatus('saved');
      setTimeout(() => setAutoSaveStatus('idle'), 2000);
    } catch (error) {
      console.error('Auto-save failed:', error);
      toast.error("Auto-save failed - Your changes couldn't be saved automatically");
      setAutoSaveStatus('idle');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Clean up form data
    const cleanedData = Object.entries(formData).reduce((acc, [key, value]) => {
      if (value !== undefined && value !== null && value !== '') {
        acc[key] = value;
      }
      return acc;
    }, {} as any);

    // Use submitForm callback pattern
    const success = await submitForm(formId, async () => {
      if (mode === 'create') {
        await createMutation.mutateAsync(cleanedData as Create${modelName}Input);
      } else if (data?.id) {
        await updateMutation.mutateAsync({
          id: data.id,
          ...cleanedData
        } as Update${modelName}Input);
      }
    });

    if (success) {
      toast.success(\`${modelName} \${mode === 'create' ? 'created' : 'updated'} successfully\`);
      onSuccess();
      destroyForm(formId);
    } else {
      ${hasSpecializedStore 
        ? `const formErrors = getFormErrors(formId);
      const allErrors = Object.values(formErrors).flat();
      if (allErrors.length > 0) {
        toast.error(\`Validation Error: \${allErrors.join(', ')}\`);
      } else {
        toast.error(\`Failed to \${mode} ${lowerName}\`);
      }`
        : `const form = getFormData(formId);
      const errors = form?.submission?.submitErrors || [];
      if (errors.length > 0) {
        toast.error(\`Validation Error: \${errors.join(', ')}\`);
      } else {
        toast.error(\`Failed to \${mode} ${lowerName}\`);
      }`}
    }
  };

  ${hasEnhancedEditor ? this.generateContentFieldsRenderer(contentFields) : ''}

  const renderMetadataFields = () => (
    <div className="space-y-4">
${editableFields.filter(field => !contentFieldNames.has(field.name)).map(field => this.generateFieldRenderer(field, enumFields, mandatoryRelations)).join('\n')}
    </div>
  );

  const renderMediaFields = () => (
    <div className="space-y-4">
      {/* Add image fields if they exist */}
${editableFields.filter(f => f.name.toLowerCase().includes('image')).map(field => `
      <AdminImageField
        value={formData.${field.name} as string || ''}
        onChange={(url) => handleChange('${field.name}', url)}
        label="${field.name.charAt(0).toUpperCase() + field.name.slice(1)}"
      />`).join('')}
      
      {/* Add multi-image fields if they exist */}
${editableFields.filter(f => f.name.toLowerCase().includes('images')).map(field => `
      <AdminMultiImageField
        value={formData.${field.name} as string[] || []}
        onChange={(urls) => handleChange('${field.name}', urls)}
        label="${field.name.charAt(0).toUpperCase() + field.name.slice(1)}"
      />`).join('')}
    </div>
  );

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="space-y-6"
    >
      {/* Auto-save Status */}
      {${hasEnhancedEditor} && autoSaveStatus !== 'idle' && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          className="flex items-center gap-2 p-3 bg-muted/50 dark:bg-gray-800/50 rounded-lg border border-border dark:border-gray-700"
        >
          {autoSaveStatus === 'saving' ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin text-primary" />
              <span className="text-sm text-muted-foreground">Auto-saving...</span>
            </>
          ) : (
            <>
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              <span className="text-sm text-green-600 dark:text-green-400">Auto-saved</span>
            </>
          )}
        </motion.div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full ${hasEnhancedEditor ? 'grid-cols-3' : 'grid-cols-2'}">
            ${hasEnhancedEditor ? `
            <TabsTrigger value="content" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Content
            </TabsTrigger>` : ''}
            <TabsTrigger value="details" className="flex items-center gap-2">
              <Settings className="h-4 w-4" />
              Details
            </TabsTrigger>
            <TabsTrigger value="media" className="flex items-center gap-2">
              <Image className="h-4 w-4" />
              Media
            </TabsTrigger>
          </TabsList>

          ${hasEnhancedEditor ? `
          <TabsContent value="content" className="space-y-6 mt-6">
            <Card className="bg-card dark:bg-gray-800 border-border dark:border-gray-700">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-foreground dark:text-white">
                  <FileText className="h-5 w-5" />
                  Content Editor
                </CardTitle>
                <CardDescription className="text-muted-foreground dark:text-gray-400">
                  Create and edit your content with our enhanced editor featuring AI assistance and markdown support
                </CardDescription>
              </CardHeader>
              <CardContent>
                {renderContentFields()}
              </CardContent>
            </Card>
          </TabsContent>` : ''}

          <TabsContent value="details" className="space-y-6 mt-6">
            <Card className="bg-card dark:bg-gray-800 border-border dark:border-gray-700">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-foreground dark:text-white">
                  <Settings className="h-5 w-5" />
                  ${modelName} Details
                </CardTitle>
                <CardDescription className="text-muted-foreground dark:text-gray-400">
                  Configure the metadata and settings for your ${lowerName}
                </CardDescription>
              </CardHeader>
              <CardContent>
                {renderMetadataFields()}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="media" className="space-y-6 mt-6">
            <Card className="bg-card dark:bg-gray-800 border-border dark:border-gray-700">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-foreground dark:text-white">
                  <Image className="h-5 w-5" />
                  Media Assets
                </CardTitle>
                <CardDescription className="text-muted-foreground dark:text-gray-400">
                  Upload and manage images and other media assets
                </CardDescription>
              </CardHeader>
              <CardContent>
                {renderMediaFields()}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        <Separator />

        {/* Form Actions */}
        <div className="flex items-center justify-between pt-4">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            {${hasEnhancedEditor} && mode === 'edit' && (
              <>
                <Clock className="h-4 w-4" />
                <span>Changes are automatically saved</span>
              </>
            )}
          </div>
          
          <div className="flex items-center gap-3">
            <Button
              type="button"
              variant="outline"
              onClick={onCancel}
              disabled={isSubmitting}
              className="border-border dark:border-gray-600"
            >
              <X className="h-4 w-4 mr-2" />
              Cancel
            </Button>
            
            <Button
              type="submit"
              disabled={isSubmitting}
              className="gradient-primary shadow-elevated hover:shadow-luxury"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {mode === 'create' ? 'Creating...' : 'Updating...'}
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  {mode === 'create' ? 'Create' : 'Update'} ${modelName}
                </>
              )}
            </Button>
          </div>
        </div>
      </form>
    </motion.div>
  );
}`;
  }

  /**
   * Generate content fields renderer
   */
  private generateContentFieldsRenderer(contentFields: ContentFieldConfig[]): string {
    return `
  const renderContentFields = () => (
    <div className="space-y-6">
${contentFields.map(field => `
      <div>
        <EnhancedContentEditor
          value={formData.${field.fieldName} || ''}
          onChange={(value) => handleChange('${field.fieldName}', value)}
          label="${field.fieldName.charAt(0).toUpperCase() + field.fieldName.slice(1)}"
          placeholder="Start writing your ${field.fieldName}..."
          required={true}
          minHeight={${field.minHeight}}
          maxHeight={${field.maxHeight}}
          showPreview={${field.enablePreview}}
          showAIAssistant={${field.enableAI}}
          autoSave={${field.enableAutoSave} && mode === 'edit'}
          onAutoSave={(content) => handleAutoSave('${field.fieldName}', content)}
          className="w-full"
        />
      </div>`).join('')}
    </div>
  );`;
  }

  /**
   * Generate field renderer for non-content fields
   */
  private generateFieldRenderer(
    field: { name: string; type: string; isOptional: boolean; isEnum?: boolean; enumValues?: string[] },
    enumFields: any[],
    mandatoryRelations: any[]
  ): string {
    const { name, type, isOptional, isEnum, enumValues } = field;
    const label = name.charAt(0).toUpperCase() + name.slice(1);
    const required = !isOptional;

    // Handle DateTime fields
    if (type === 'DateTime') {
      return `
      <div>
        <Label htmlFor="${name}" className="text-foreground dark:text-white">
          ${label}
          ${required ? '<span className="text-destructive dark:text-red-400">*</span>' : ''}
        </Label>
        <Input
          id="${name}"
          type="datetime-local"
          value={formData.${name} ? new Date(formData.${name}).toISOString().slice(0, 16) : ''}
          onChange={(e) => handleChange('${name}', e.target.value ? new Date(e.target.value).toISOString() : ${isOptional ? 'null' : "''"} )}
          placeholder="Enter ${label.toLowerCase()}"
          className="bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600"
          ${required ? 'required' : ''}
        />
      </div>`;
    }

    // Handle enum fields - Enhanced with responsive styling
    if (isEnum && enumValues) {
      return `
      <div className="w-full">
        <Label htmlFor="${name}" className="text-foreground dark:text-white mb-2 block">
          ${label}
          ${required ? '<span className="text-destructive dark:text-red-400">*</span>' : ''}
        </Label>
        <Select value={formData.${name} || ''} onValueChange={(value) => handleChange('${name}', value.toUpperCase())}>
          <SelectTrigger className="w-full bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600 hover:bg-orange-600/10 dark:hover:bg-orange-500/20 hover:text-orange-700 dark:hover:text-orange-300 hover:border-orange-600/30 dark:hover:border-orange-400/40 transition-colors duration-200">
            <SelectValue placeholder="Select ${label.toLowerCase()}" />
          </SelectTrigger>
          <SelectContent className="bg-background dark:bg-gray-900 border-border dark:border-gray-600 max-h-[300px] overflow-y-auto">
            ${enumValues.map(value => `
            <SelectItem 
              key="${value}" 
              value="${value}"
              className="focus:bg-orange-600/10 dark:focus:bg-orange-500/20 focus:text-orange-700 dark:focus:text-orange-300 transition-colors duration-200 cursor-pointer"
            >
              ${value}
            </SelectItem>`).join('')}
          </SelectContent>
        </Select>
      </div>`;
    }

    // Handle relation fields - Enhanced with API fetching and loading states
    const relation = mandatoryRelations.find(r => r.name === name);
    if (relation) {
      const relModel = relation.model;
      const relLower = relModel.charAt(0).toLowerCase() + relModel.slice(1);
      const loadingVar = `${relLower}Loading`;
      const errorVar = `${relLower}Error`;
      return `
      <div className="w-full">
        <Label htmlFor="${name}" className="text-foreground dark:text-white mb-2 block">
          ${label}
          ${required ? '<span className="text-destructive dark:text-red-400">*</span>' : ''}
        </Label>
        <Select 
          value={formData.${name} || ''} 
          onValueChange={(value) => handleChange('${name}', value)}
          disabled={${loadingVar}}
        >
          <SelectTrigger className="w-full bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600 hover:bg-orange-600/10 dark:hover:bg-orange-500/20 hover:text-orange-700 dark:hover:text-orange-300 hover:border-orange-600/30 dark:hover:border-orange-400/40 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed">
            <SelectValue placeholder={${loadingVar} ? 'Loading...' : 'Select ${label.toLowerCase()}'} />
          </SelectTrigger>
          <SelectContent className="bg-background dark:bg-gray-900 border-border dark:border-gray-600 max-h-[300px] overflow-y-auto">
            {${loadingVar} ? (
              <div className="p-4 text-center text-muted-foreground dark:text-gray-400">
                <Loader2 className="h-4 w-4 animate-spin mx-auto mb-2" />
                Loading options...
              </div>
            ) : ${errorVar} ? (
              <div className="p-4 text-center text-destructive dark:text-red-400 text-sm">
                Failed to load options
              </div>
            ) : ${relLower}Options && ${relLower}Options.length > 0 ? (
              ${relLower}Options.map((option: any) => (
                <SelectItem 
                  key={option.id} 
                  value={option.id}
                  className="focus:bg-orange-600/10 dark:focus:bg-orange-500/20 focus:text-orange-700 dark:focus:text-orange-300 transition-colors duration-200 cursor-pointer"
                >
                  {option.name || option.title || option.email || option.id}
                </SelectItem>
              ))
            ) : (
              <div className="p-4 text-center text-muted-foreground dark:text-gray-400 text-sm">
                No options available
              </div>
            )}
          </SelectContent>
        </Select>
      </div>`;
    }

    // Handle boolean fields
    if (type === 'Boolean') {
      return `
      <div>
        <Label htmlFor="${name}" className="text-foreground dark:text-white">
          ${label}
        </Label>
        <Select value={formData.${name}?.toString() || 'false'} onValueChange={(value) => handleChange('${name}', value === 'true')}>
          <SelectTrigger className="bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600">
            <SelectValue placeholder="Select ${label.toLowerCase()}" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="true">Yes</SelectItem>
            <SelectItem value="false">No</SelectItem>
          </SelectContent>
        </Select>
      </div>`;
    }

    // Handle textarea fields (for longer text that's not content)
    if (name.toLowerCase().includes('note') || name.toLowerCase().includes('comment') || name.toLowerCase().includes('message')) {
      return `
      <div>
        <Label htmlFor="${name}" className="text-foreground dark:text-white">
          ${label}
          ${required ? '<span className="text-destructive dark:text-red-400">*</span>' : ''}
        </Label>
        <Textarea
          id="${name}"
          value={formData.${name} as string || ''}
          onChange={(e) => handleChange('${name}', e.target.value)}
          placeholder="Enter ${label.toLowerCase()}"
          className="bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600"
          rows={3}
          ${required ? 'required' : ''}
        />
      </div>`;
    }

    // Default to input field
    const inputType = type === 'Int' || type === 'Float' ? 'number' : 
                     name.toLowerCase().includes('email') ? 'email' :
                     name.toLowerCase().includes('url') ? 'url' :
                     name.toLowerCase().includes('phone') ? 'tel' : 'text';

    return `
      <div>
        <Label htmlFor="${name}" className="text-foreground dark:text-white">
          ${label}
          ${required ? '<span className="text-destructive dark:text-red-400">*</span>' : ''}
        </Label>
        <Input
          id="${name}"
          type="${inputType}"
          value={formData.${name} as any || ''}
          onChange={(e) => handleChange('${name}', ${inputType === 'number' ? 'parseFloat(e.target.value) || 0' : 'e.target.value'})}
          placeholder="Enter ${label.toLowerCase()}"
          className="bg-background dark:bg-gray-900 text-foreground dark:text-white border-border dark:border-gray-600"
          ${required ? 'required' : ''}
        />
      </div>`;
  }

  /**
   * Write enhanced form to file
   */
  writeEnhancedForm(config: EnhancedFormConfig): void {
    const { modelName } = config;
    const lowerName = modelName.charAt(0).toLowerCase() + modelName.slice(1);
    
    const formDir = join(this.baseDir, 'forms');
    if (!existsSync(formDir)) {
      mkdirSync(formDir, { recursive: true });
    }

    const formPath = join(formDir, `enhanced-${lowerName}-form.tsx`);
    const formContent = this.generateEnhancedForm(config);
    
    writeFileSync(formPath, formContent, 'utf8');
    console.log(`✅ Generated enhanced form: ${formPath}`);
  }

  /**
   * Generate enhanced form for a model
   */
  generateForModel(
    modelName: string,
    fields: Array<{ name: string; type: string; isOptional: boolean; isEnum?: boolean; enumValues?: string[] }>,
    relations: Array<{ name: string; model: string; type: string; isOptional: boolean }> = [],
    databaseFirst: boolean = false
  ): void {
    const contentFields = getModelContentFields(modelName, fields);
    const hasEnhancedEditor = shouldUseEnhancedContentEditor(modelName, fields);

    if (!hasEnhancedEditor) {
      console.log(`⚠️  ${modelName} does not require enhanced content editor, skipping...`);
      return;
    }

    const config: EnhancedFormConfig = {
      modelName,
      fields,
      relations,
      contentFields,
      hasEnhancedEditor,
      databaseFirst
    };

    this.writeEnhancedForm(config);
  }
}
