// Auto-generated by CustomRouteGenerator
// DO NOT EDIT - Auto-generated custom route
// ✅ ZenStack v3 ORM: Uses createClient(user) not PrismaClient
// ✅ Access Control: Respects ZenStack @@allow/@@deny rules

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/db";
import { initializeNewUser } from "@/lib/services/user-initialization";
import { getStoredOTP, deleteStoredOTP } from "@/lib/auth/otp-storage";
import type { AuthUser } from "@/lib/auth";

/**
 * Verify OTP and authenticate user
 * POST /api/auth/email/verify-otp
 */
export async function POST(request: NextRequest) {
  try {
    const { email, otp } = await request.json();

    if (!email || !otp) {
      return NextResponse.json(
        { error: "Email and OTP are required" },
        { status: 400 }
      );
    }

    const systemUser: AuthUser = {
      id: 'system',
      email: 'system@TKNZN.pro',
      name: 'System Admin',
      role: 'ADMIN' as const,
    };
    const db = await createClient(systemUser);
    const normalizedEmail = email.toLowerCase().trim();

    // Verify OTP from storage
    const storedOTP = await getStoredOTP(normalizedEmail);
    
    if (!storedOTP) {
      return NextResponse.json(
        { error: "No OTP request found for this email. Please request a new OTP." },
        { status: 404 }
      );
    }

    // Check if OTP expired
    if (new Date(storedOTP.expiresAt) < new Date()) {
      await deleteStoredOTP(normalizedEmail);
      return NextResponse.json(
        { error: "OTP has expired. Please request a new OTP." },
        { status: 401 }
      );
    }

    // Verify OTP matches
    if (storedOTP.otp !== otp) {
      return NextResponse.json(
        { error: "Invalid OTP. Please check and try again." },
        { status: 401 }
      );
    }

    // OTP verified successfully - delete it
    await deleteStoredOTP(normalizedEmail);

    // Find or create user
    let user = await db.user.findUnique({
      where: { email: normalizedEmail },
      include: {
        accounts: true,
        preferences: true,
        userQtechAccount: true,
        portfolio: true,
        engagementMetrics: true,
        addressBooks: true,
      },
    });

    const isNewUser = !user;

    if (!user) {
      // Create new user
      const newUser = await db.user.create({
        data: {
          email: normalizedEmail,
          name: normalizedEmail.split('@')[0],
          role: 'CUSTOMER',
          emailVerified: new Date(),
        },
      });
      console.log('✅ [Email OTP] Created new user:', newUser.id);
      
      // Fetch user with relations for completeness check
      user = await db.user.findUnique({
        where: { id: newUser.id },
        include: {
          accounts: true,
          preferences: true,
          userQtechAccount: true,
          portfolio: true,
          engagementMetrics: true,
          addressBooks: true,
        },
      });
    }

    if (!user) {
      throw new Error('Failed to create or fetch user');
    }

    // Check if user needs dependency initialization
    const missingRecords: string[] = [];
    if (!user.accounts || user.accounts.length === 0) missingRecords.push('account');
    if (!user.preferences) missingRecords.push('preferences');
    if (!user.userQtechAccount || user.userQtechAccount.length === 0) missingRecords.push('userQtechAccount');
    if (!user.portfolio || user.portfolio.length === 0) missingRecords.push('portfolio');
    if (!user.engagementMetrics) missingRecords.push('engagementMetrics');
    if (!user.addressBooks || user.addressBooks.length === 0) missingRecords.push('addressBooks');

    // Initialize dependencies if needed (new user or missing records)
    if (isNewUser || missingRecords.length > 0) {
      const ipAddress = request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || 'unknown';
      const userAgent = request.headers.get('user-agent') || undefined;
      
      try {
        const initResult = await initializeNewUser({
          userId: user.id,
          email: user.email || normalizedEmail,
          name: user.name || normalizedEmail.split('@')[0],
          authMethod: 'email',
          ipAddress,
          userAgent,
        });
        
        if (initResult.success) {
          console.log('✅ [Email OTP] User dependencies initialized:', {
            isNewUser,
            missingRecords,
            accountCreated: !!initResult.account,
            preferencesCreated: !!initResult.preferences,
            activityLogged: initResult.activityLogged,
          });
        } else {
          console.warn('⚠️ [Email OTP] User initialization had errors:', initResult.errors);
        }
      } catch (initError) {
        console.error('❌ [Email OTP] Error initializing user dependencies:', initError);
        // Don't fail authentication if initialization fails - user can still login
      }
    }

    // Update user email verification and auth method
    const updatedUser = await db.user.update({
      where: { id: user.id },
      data: {
        emailVerified: new Date(),
        authMethod: user.authMethod?.includes('email') ? user.authMethod : 
                    user.authMethod ? `${user.authMethod},email` : 'email',
      },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        authMethod: true,
      },
    });

    return NextResponse.json({
      success: true,
      user: {
        id: updatedUser.id,
        email: updatedUser.email,
        name: updatedUser.name,
        role: updatedUser.role || 'CUSTOMER',
        authMethod: updatedUser.authMethod || 'email',
      },
      isNewUser,
    });

  } catch (error) {
    console.error('❌ [Email OTP] Error verifying OTP:', error);
    return NextResponse.json(
      { error: "Failed to verify OTP" },
      { status: 500 }
    );
  }
}

