#!/usr/bin/env tsx
/**
 * Sync Contract Addresses
 * 
 * Updates all contract addresses across codebase, configuration files, and .env files
 * to match the latest deployed addresses from deployed-addresses-proxy.json
 * 
 * Usage:
 *   cd smart-contracts
 *   bun run tsx scripts/sync-contract-addresses.ts
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';

const DEPLOYED_ADDRESSES_FILE = path.join(__dirname, '../deployed-addresses-proxy.json');
const PRICE_ORACLE_ADDRESS = '0x2dF640767e42136809Fa0Ee787F24A2b92191B02'; // ChainlinkPriceOracle
const USDC_ADDRESS = '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238';
const EURC_ADDRESS = '0x08210F9170F89Ab7658F0B5E3fF39b0E03C594D4';

interface DeploymentAddresses {
  network: string;
  addresses: {
    ProxyAdmin: string;
    RWAAssetRegistry: string;
    RWATokenFactory: string;
    RWATokenFactory404: string;
    RWAMarketplace: string;
    RWAStaking: string;
    RWARewardDistributor: string;
    RWARevenue: string;
    MembershipSystem: string;
    TigerPalaceToken: string;
    [key: string]: string;
  };
}

function loadDeployedAddresses(): DeploymentAddresses {
  if (!fs.existsSync(DEPLOYED_ADDRESSES_FILE)) {
    throw new Error(`Deployed addresses file not found: ${DEPLOYED_ADDRESSES_FILE}`);
  }
  return JSON.parse(fs.readFileSync(DEPLOYED_ADDRESSES_FILE, 'utf-8'));
}

function generateEnvFile(addresses: DeploymentAddresses, outputPath: string): void {
  const envLines: string[] = [
    '# Tiger Palace Pro - Sepolia Testnet Contract Addresses',
    '# Auto-generated by sync-contract-addresses.ts',
    `# Last updated: ${new Date().toISOString()}`,
    '',
    '# Proxy Admin',
    `SEPOLIA_PROXY_ADMIN=${addresses.addresses.ProxyAdmin}`,
    `NEXT_PUBLIC_PROXY_ADMIN_ADDRESS=${addresses.addresses.ProxyAdmin}`,
    '',
    '# Core Contracts (Proxy addresses - use these)',
    `RWA_ASSET_REGISTRY=${addresses.addresses.RWAAssetRegistry}`,
    `NEXT_PUBLIC_RWA_ASSET_REGISTRY=${addresses.addresses.RWAAssetRegistry}`,
    `NEXT_PUBLIC_RWA_ASSET_REGISTRY_ADDRESS=${addresses.addresses.RWAAssetRegistry}`,
    '',
    `RWA_TOKEN_FACTORY=${addresses.addresses.RWATokenFactory}`,
    `NEXT_PUBLIC_RWA_TOKEN_FACTORY=${addresses.addresses.RWATokenFactory}`,
    `NEXT_PUBLIC_RWA_TOKEN_FACTORY_ADDRESS=${addresses.addresses.RWATokenFactory}`,
    '',
    `RWA_TOKEN_FACTORY_404=${addresses.addresses.RWATokenFactory404}`,
    `NEXT_PUBLIC_RWA_TOKEN_FACTORY_404=${addresses.addresses.RWATokenFactory404}`,
    `NEXT_PUBLIC_RWA_TOKEN_FACTORY_404_ADDRESS=${addresses.addresses.RWATokenFactory404}`,
    '',
    `RWA_MARKETPLACE=${addresses.addresses.RWAMarketplace}`,
    `NEXT_PUBLIC_RWA_MARKETPLACE=${addresses.addresses.RWAMarketplace}`,
    `NEXT_PUBLIC_RWA_MARKETPLACE_ADDRESS=${addresses.addresses.RWAMarketplace}`,
    '',
    '# Staking Contracts',
    `RWA_STAKING=${addresses.addresses.RWAStaking}`,
    `NEXT_PUBLIC_RWA_STAKING=${addresses.addresses.RWAStaking}`,
    `NEXT_PUBLIC_RWA_STAKING_ADDRESS=${addresses.addresses.RWAStaking}`,
    '',
    `RWA_REWARD_DISTRIBUTOR=${addresses.addresses.RWARewardDistributor}`,
    `NEXT_PUBLIC_RWA_REWARD_DISTRIBUTOR=${addresses.addresses.RWARewardDistributor}`,
    `NEXT_PUBLIC_RWA_REWARD_DISTRIBUTOR_ADDRESS=${addresses.addresses.RWARewardDistributor}`,
    '',
    `RWA_REVENUE=${addresses.addresses.RWARevenue}`,
    `NEXT_PUBLIC_RWA_REVENUE=${addresses.addresses.RWARevenue}`,
    `NEXT_PUBLIC_RWA_REVENUE_ADDRESS=${addresses.addresses.RWARevenue}`,
    '',
    '# Membership System',
    `MEMBERSHIP_SYSTEM=${addresses.addresses.MembershipSystem}`,
    `NEXT_PUBLIC_MEMBERSHIP_SYSTEM=${addresses.addresses.MembershipSystem}`,
    `NEXT_PUBLIC_MEMBERSHIP_SYSTEM_ADDRESS=${addresses.addresses.MembershipSystem}`,
    '',
    '# Token Addresses',
    `TIGER_PALACE_TOKEN=${addresses.addresses.TigerPalaceToken}`,
    `NEXT_PUBLIC_TPT_ADDRESS=${addresses.addresses.TigerPalaceToken}`,
    '',
    '# Payment Tokens',
    `NEXT_PUBLIC_USDC_ADDRESS=${USDC_ADDRESS}`,
    `NEXT_PUBLIC_EURC_ADDRESS=${EURC_ADDRESS}`,
    '',
    '# Price Oracle',
    `CHAINLINK_PRICE_ORACLE=${PRICE_ORACLE_ADDRESS}`,
    `NEXT_PUBLIC_CHAINLINK_PRICE_ORACLE=${PRICE_ORACLE_ADDRESS}`,
    '',
    '# Implementation Addresses (for reference)',
    `RWA_ASSET_REGISTRY_IMPL=${addresses.addresses.RWAAssetRegistry_Implementation || ''}`,
    `RWA_TOKEN_FACTORY_IMPL=${addresses.addresses.RWATokenFactory_Implementation || ''}`,
    `RWA_MARKETPLACE_IMPL=${addresses.addresses.RWAMarketplace_Implementation || ''}`,
    `RWA_STAKING_IMPL=${addresses.addresses.RWAStaking_Implementation || ''}`,
    `MEMBERSHIP_SYSTEM_IMPL=${addresses.addresses.MembershipSystem_Implementation || ''}`,
    '',
    '# Network Configuration',
    'NEXT_PUBLIC_CHAIN_ID=11155111',
    'NEXT_PUBLIC_NETWORK=sepolia',
    '',
    '# RPC Configuration',
    'SEPOLIA_RPC_URL=https://rpc.sepolia.org',
    'NEXT_PUBLIC_SEPOLIA_RPC_URL=https://rpc.sepolia.org',
  ];

  fs.writeFileSync(outputPath, envLines.join('\n') + '\n');
}

async function main() {
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║   SYNC CONTRACT ADDRESSES                                  ║');
  console.log('╚════════════════════════════════════════════════════════════╝\n');

  const addresses = loadDeployedAddresses();
  console.log(`📋 Loaded addresses from: ${DEPLOYED_ADDRESSES_FILE}`);
  console.log(`   Network: ${addresses.network}\n`);

  // Generate .env.local files
  const rootPath = path.resolve(__dirname, '../../..');
  const rootEnvLocal = path.join(rootPath, '.env.local');
  const contractsEnvLocal = path.join(__dirname, '../.env.local');
  const envExample = path.join(__dirname, '../env.local.example');

  console.log(`📝 Generating environment files...`);
  generateEnvFile(addresses, rootEnvLocal);
  console.log(`   ✅ ${rootEnvLocal}`);
  
  generateEnvFile(addresses, contractsEnvLocal);
  console.log(`   ✅ ${contractsEnvLocal}`);
  
  generateEnvFile(addresses, envExample);
  console.log(`   ✅ ${envExample}\n`);

  // Update verify-frontend-assets.ts with price oracle address
  const verifyScript = path.join(__dirname, 'verify-frontend-assets.ts');
  if (fs.existsSync(verifyScript)) {
    let content = fs.readFileSync(verifyScript, 'utf-8');
    const oldOraclePattern = /const priceOracleAddress = ['"]0x[A-Fa-f0-9]{40}['"]; \/\/ From deployment/;
    if (oldOraclePattern.test(content)) {
      content = content.replace(
        oldOraclePattern,
        `const priceOracleAddress = '${PRICE_ORACLE_ADDRESS}'; // ChainlinkPriceOracle`
      );
      fs.writeFileSync(verifyScript, content);
      console.log(`   ✅ Updated ${verifyScript} with price oracle address`);
    }
  }

  // Summary
  console.log(`\n📊 Contract Addresses Summary:\n`);
  console.log(`   ProxyAdmin: ${addresses.addresses.ProxyAdmin}`);
  console.log(`   RWAAssetRegistry: ${addresses.addresses.RWAAssetRegistry}`);
  console.log(`   RWATokenFactory: ${addresses.addresses.RWATokenFactory}`);
  console.log(`   RWATokenFactory404: ${addresses.addresses.RWATokenFactory404}`);
  console.log(`   RWAMarketplace: ${addresses.addresses.RWAMarketplace}`);
  console.log(`   RWAStaking: ${addresses.addresses.RWAStaking}`);
  console.log(`   RWARewardDistributor: ${addresses.addresses.RWARewardDistributor}`);
  console.log(`   RWARevenue: ${addresses.addresses.RWARevenue}`);
  console.log(`   MembershipSystem: ${addresses.addresses.MembershipSystem}`);
  console.log(`   TigerPalaceToken: ${addresses.addresses.TigerPalaceToken}`);
  console.log(`   ChainlinkPriceOracle: ${PRICE_ORACLE_ADDRESS}`);
  console.log(`   USDC: ${USDC_ADDRESS}`);
  console.log(`   EURC: ${EURC_ADDRESS}\n`);

  console.log('✅ Address sync complete!\n');
  console.log('📝 Next steps:');
  console.log('   1. Review generated .env.local files');
  console.log('   2. Restart development server if running');
  console.log('   3. Verify frontend can access contracts\n');
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('\n❌ Sync failed:', error);
    process.exit(1);
  });

