// Auto-generated by CustomRouteGenerator
// DO NOT EDIT - Auto-generated custom route
// ✅ ZenStack v3 ORM: Uses createClient(user) not PrismaClient
// ✅ Access Control: Respects ZenStack @@allow/@@deny rules

import { createClient } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';
import { AuditActivityLogger } from '@/lib/services/audit-activity-logger';
import type { AuthUser } from '@/lib/auth';
import { UserRole } from '@/lib/user-activity-logger';
/**
 * POST /api/auth/logout/audit - Create audit log entry for user logout
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { userId, walletAddress, authMethod, timestamp } = body;

    if (!userId) {
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      );
    }

    console.log('📝 Creating logout audit log for user:', userId);

    // Get session metadata
    const userAgent = request.headers.get('user-agent') || undefined;
    const ipAddress = request.headers.get('x-forwarded-for') || 
                     request.headers.get('x-real-ip') || 
                     'unknown';

    const systemUser: AuthUser = {
      id: 'system',
      email: 'system@TKNZN.pro',
      name: 'System Admin',
      role: 'ADMIN' as any as UserRole,
    };
    const db = await createClient(systemUser);

    // Fetch user details to determine session duration
    const user = await db.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        lastLoginAt: true, // Use lastLoginAt instead of lastWalletSignIn
      },
    });

    if (!user) {
      return NextResponse.json(
        { error: 'User not found' },
        { status: 404 }
      );
    }

    // Calculate session duration if we have login timestamp
    let sessionDuration: number | undefined;
    if (user.lastLoginAt) {
      sessionDuration = Date.now() - user.lastLoginAt.getTime();
    }

    // Use unified audit/activity logger
    await AuditActivityLogger.logLogout(
      userId,
      undefined, // sessionId
      sessionDuration,
      ipAddress,
      userAgent
    );

    console.log('✅ Logout audit log created');

    // Update user's last activity timestamp
    await db.user.update({
      where: { id: userId },
      data: {
        updatedAt: new Date(),
      },
    });

    // If wallet was connected, mark sessions as inactive
    if (walletAddress) {
      // Try 'session' first (new generic model), fallback to 'walletSession' if schema not updated yet
      let inactivatedSessions;
      try {
        inactivatedSessions = await db.session.updateMany({
          where: {
            userId,
            walletAddress: walletAddress.toLowerCase(),
            isActive: true,
          },
          data: {
            isActive: false,
            lastUsedAt: new Date(),
          },
        });
      } catch (error: any) {
        // Fallback: If session model doesn't exist, try walletSession (backward compatibility)
        if (error.message?.includes('session') || error.message?.includes('Session') || error.message?.includes('undefined')) {
          console.warn('⚠️ [Logout Audit] session model not found, trying walletSession (schema may not be updated yet)');
          // @ts-ignore - walletSession may still exist in schema
          if (db.walletSession) {
            inactivatedSessions = await db.walletSession.updateMany({
              where: {
                userId,
                walletAddress: walletAddress.toLowerCase(),
                isActive: true,
              },
              data: {
                isActive: false,
                lastUsedAt: new Date(),
              },
            });
          } else {
            console.warn('⚠️ [Logout Audit] Neither session nor walletSession model found, skipping session inactivation');
            inactivatedSessions = { count: 0 };
          }
        } else {
          throw error;
        }
      }

      console.log(`🔌 Inactivated ${inactivatedSessions.count} wallet sessions`);
    }

    return NextResponse.json({
      success: true,
      message: 'Logout audit log created successfully',
    });

  } catch (error) {
    console.error('❌ Error creating logout audit log:', error);
    return NextResponse.json(
      { 
        error: 'Failed to create audit log',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
