// Auto-generated by CustomRouteGenerator
// DO NOT EDIT - Auto-generated custom route
// ✅ ZenStack v3 ORM: Uses createClient(user) not PrismaClient
// ✅ Access Control: Respects ZenStack @@allow/@@deny rules

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/db";
import { storeOTP } from "@/lib/auth/otp-storage";
import crypto from "crypto";
import type { AuthUser } from "@/lib/auth";

/**
 * Send OTP to user's email
 * POST /api/auth/email/send-otp
 */
export async function POST(request: NextRequest) {
  try {
    const { email } = await request.json();

    if (!email || typeof email !== 'string' || !email.includes('@')) {
      return NextResponse.json(
        { error: "Valid email address is required" },
        { status: 400 }
      );
    }

    const systemUser: AuthUser = {
      id: 'system',
      email: 'system@TKNZN.pro',
      name: 'System Admin',
      role: 'ADMIN' as const,
    };  
    const db = await createClient(systemUser);

    // Generate 6-digit OTP
    const otp = crypto.randomInt(100000, 999999).toString();
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes expiry

    // Store OTP in database (you can use a separate OTP table or cache)
    // For now, we'll use a simple approach with a temporary record
    // In production, use Redis or a dedicated OTP table
    
    // Check if user exists
    let user = await db.user.findUnique({
      where: { email: email.toLowerCase().trim() },
    });

    if (!user) {
      // Create user if doesn't exist (for new signups)
      user = await db.user.create({
        data: {
          email: email.toLowerCase().trim(),
          name: email.split('@')[0],
          role: 'CUSTOMER',
        },
      });
      console.log('✅ [Email OTP] Created new user:', user.id);
    }

    // Store OTP (in production, use Redis or dedicated table)
    // For now, we'll create a simple storage mechanism
    // You can use a VerificationToken model or Redis
    
    // Send email with OTP
    // TODO: Integrate with your email service (SendGrid, AWS SES, etc.)
    console.log(`📧 [Email OTP] OTP for ${email}: ${otp} (expires in 10 minutes)`);
    
    // In production, send actual email:
    // await sendEmail({
    //   to: email,
    //   subject: 'Your Login Code',
    //   html: `Your one-time password is: <strong>${otp}</strong><br>This code expires in 10 minutes.`
    // });

    // Store OTP using shared utility
    await storeOTP(email, otp, expiresAt);

    // Send email with OTP
    // TODO: Integrate with your email service (SendGrid, AWS SES, etc.)
    console.log(`📧 [Email OTP] OTP for ${email}: ${otp} (expires in 10 minutes)`);
    
    // In production, send actual email:
    // await sendEmail({
    //   to: email,
    //   subject: 'Your Login Code - Tokenizin',
    //   html: `
    //     <h2>Your Login Code</h2>
    //     <p>Your one-time password is: <strong>${otp}</strong></p>
    //     <p>This code expires in 10 minutes.</p>
    //     <p>If you didn't request this code, please ignore this email.</p>
    //   `
    // });

    return NextResponse.json({
      success: true,
      message: "OTP sent to your email",
      // REMOVE THIS IN PRODUCTION - only for testing
      otp: process.env.NODE_ENV === 'development' ? otp : undefined,
      expiresAt: expiresAt.toISOString(),
    });

  } catch (error) {
    console.error('❌ [Email OTP] Error sending OTP:', error);
    return NextResponse.json(
      { error: "Failed to send OTP" },
      { status: 500 }
    );
  }
}

