// Auto-generated hook template based on current patterns
// Last synced: 2026-03-01T09:29:34.595Z
// This template can be used to generate/regenerate React Query hooks for entities

// @ts-nocheck - Template file: imports resolve when used in component location

// Generated Hooks for {{modelName}}
// DO NOT EDIT - Auto-generated by CompleteEntityGenerator

'use client';

import { useQuery, useMutation, useQueryClient, useInfiniteQuery, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import type { {{modelName}}, Create{{modelName}}Input, Update{{modelName}}Input, {{modelName}}Filter, {{modelName}}SortOrder, {{modelName}}WithRelations } from '../types/{{lowerModelName}}-types';
import { {{lowerModelName}}Api } from '../api/{{lowerModelName}}/{{lowerModelName}}Api';

/**
 * Hook to fetch a single {{modelName}} by ID
 */
export function use{{modelName}}(
  id: string | undefined,
  options?: Omit<UseQueryOptions<{{modelName}} | null>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['{{lowerModelName}}', id],
    queryFn: () => id ? {{lowerModelName}}Api.getById(id) : null,
    enabled: !!id,
    ...options
  });
}

/**
 * Hook to fetch {{modelName}} list with filtering and sorting
 */
export function use{{modelName}}List(
  filter?: {{modelName}}Filter,
  sortOrder?: {{modelName}}SortOrder,
  options?: Omit<UseQueryOptions<{{modelName}}[]>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['{{lowerModelName}}', 'list', filter, sortOrder],
    queryFn: () => {{lowerModelName}}Api.getAll(filter, sortOrder),
    ...options
  });
}

/**
 * Hook to fetch {{modelName}} with relations
 */
export function use{{modelName}}WithRelations(
  id: string | undefined,
  options?: Omit<UseQueryOptions<{{modelName}}WithRelations | null>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['{{lowerModelName}}', 'withRelations', id],
    queryFn: () => id ? {{lowerModelName}}Api.getWithRelations(id) : null,
    enabled: !!id,
    ...options
  });
}

/**
 * Hook to create a new {{modelName}}
 */
export function useCreate{{modelName}}(
  options?: UseMutationOptions<{{modelName}}, Error, Create{{modelName}}Input>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: Create{{modelName}}Input) => {{lowerModelName}}Api.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['{{lowerModelName}}'] });
    },
    ...options
  });
}

/**
 * Hook to update an existing {{modelName}}
 */
export function useUpdate{{modelName}}(
  options?: UseMutationOptions<{{modelName}}, Error, Update{{modelName}}Input>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: Update{{modelName}}Input) => {{lowerModelName}}Api.update(data.id, data),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['{{lowerModelName}}'] });
      queryClient.setQueryData(['{{lowerModelName}}', data.id], data);
    },
    ...options
  });
}

/**
 * Hook to delete a {{modelName}}
 */
export function useDelete{{modelName}}(
  options?: UseMutationOptions<void, Error, string>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => {{lowerModelName}}Api.delete(id),
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: ['{{lowerModelName}}'] });
      queryClient.removeQueries({ queryKey: ['{{lowerModelName}}', id] });
    },
    ...options
  });
}

/**
 * Hook for paginated {{modelName}} list
 */
export function use{{modelName}}Paginated(
  page: number = 1,
  pageSize: number = 20,
  filter?: {{modelName}}Filter,
  sortOrder?: {{modelName}}SortOrder,
  options?: Omit<UseQueryOptions<{ data: {{modelName}}[]; total: number; page: number; pageSize: number }>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: ['{{lowerModelName}}', 'paginated', page, pageSize, filter, sortOrder],
    queryFn: () => {{lowerModelName}}Api.getPaginated(page, pageSize, filter, sortOrder),
    ...options
  });
}

/**
 * Hook for infinite scroll {{modelName}} list
 */
export function use{{modelName}}Infinite(
  pageSize: number = 20,
  filter?: {{modelName}}Filter,
  sortOrder?: {{modelName}}SortOrder
) {
  return useInfiniteQuery({
    queryKey: ['{{lowerModelName}}', 'infinite', filter, sortOrder],
    queryFn: ({ pageParam = 1 }) => 
      {{lowerModelName}}Api.getPaginated(pageParam, pageSize, filter, sortOrder),
    getNextPageParam: (lastPage) => 
      lastPage.page * lastPage.pageSize < lastPage.total ? lastPage.page + 1 : undefined,
    initialPageParam: 1
  });
}
